### ISSUE TITLE
DataWriters in BlockOutStream write sequentially

### ISSUE THREAD

**Issue by ghost** [Alluxio/alluxio#10098]
**Summary**
When using `ASYNC_THROUGH`, `BlockOutStream` will write blocks into several replications, current implementation hold a `List<DataWriter>` in `BlockOutStream`, which writes data in a `for` loop over the `DataWriter`s.

**Urgency**
 Replicating to N workers takes N times than writing to one worker. This replication operation can be made asynchronous and concurrent to bootstrap throughput of replication.

**Comment by apc999** [comment]
Change this to feature request. 
Thanks for the feedback. It is not surprising that writing <N> copies of a block sync can be slower than writing them in a async way (similar to HDFS). But there are pros and cons. In this case, do you already see a slow down because of the N-copy sync write as a bottleneck?

**Comment by chcn** [comment]
@apc999 no, I didn't observe this in production, I just come up with this idea when reading the codebase.

**Comment by yuzhu** [comment]
@apc999 Do we want to consider parallel block write to N workers?
