### ISSUE TITLE
Provide more descriptive information when gRPC channel is closed

### ISSUE THREAD

**Issue by ghost** [Alluxio/alluxio#10134]
**Summary**
For example, when shutting down the `JobWorker`, `Master` will log `2019-10-16 22:06:56,814 WARN  SaslStreamServerDriver - Error received for channel: 8f6cfd81-4299-4d2c-b2a4-3c97d6b1ea80. Error: io.grpc.StatusRuntimeException: CANCELLED: cancelled before receiving half close`, but the information in this log message is not very helpful for admins to under what happened.

**Comment by yuzhu** [comment]
@ggezer I think i have seen this before as well in the log messages. Can we clean up this log message?

**Comment by ggezer** [comment]
Cancellation can be due to many reasons. Because gRPC streams can't be associated with channels/servers using its client APIs, we don't have a way to intelligently prune these messages.

I tested this particular issue and it happens only when job_worker is force killed. Then this message is expected and useful.
