### ISSUE TITLE
Helm install creates unnecessary resources

### ISSUE THREAD

**Issue by madanadit** [Alluxio/alluxio#10321]
**Alluxio Version:**
2.1.0-SNAPSHOT

**Describe the bug**
Helm install creates everything under the directory `helm-chart/alluxio/templates/`. Some of these resources / jobs should not be created by default and made configurable.

1. Is this still needed `helm-chart/alluxio/templates/format/master.yaml` or can we remove it?
2. `helm install` run the fuse daemonset and client daemonset by default, both should be made configurable and false by default. 
```
fuse:
  enabled: true
  clientEnabled: true
```
3. `job/format-journal-job.yaml` is run by default when `helm install` is run. how should we disable it and invoke it on demand?
4. `master/journal-pv.yaml` and `master/journal-pvc.yaml` are created by default even when using configs which don't use it. This should also be disabled when not needed.

**To Reproduce**
Run `helm install` and look at the resources / jobs created using `kubectl`

**Expected behavior**
N/A

**Urgency**
N/A

**Additional context**
N/A

**Comment by jiacheliu3** [comment]
Regarding the action items:

1. `helm-chart/alluxio/templates/format/master.yaml` is removed. We don't really need it in the template deployment.

2.(and 3. and 4.) As far as I found out the ONLY way to make `helm install` NOT create every single resource it can find is to make helm not see it, by excluding those files in `.helmignore`. As long as you have that file under the `templates/` directory I didn't think of an easy way to switch it ON/OFF. 
If `fuse/` and `job/` shouldn't be run they can be added to `.helmignore`.

To make matters worse, files defined in `.helmignore` will be ignored by `helm template`. We need `helm template` to generate templates in `job/` and `fuse/`. That's why I don't want to include these two dirs in `.helmignore`.

So as you see, `.helmignore` affects `helm install` and `helm template` together (even though the doc says this only affects the packaging step). We cannot make something ignored only for `helm install`. 

I lean towards NOT adding these 2 directories in `.helmignore` and explain in `Deploy using helm` how the user can make Helm not create the resource they don't need.

**Comment by madanadit** [comment]
@jiacheliu3 @ZacBlanco not targeting this PR to 2.1.

**Comment by calvinjia** [comment]
@madanadit Are we still planning to address this issue?

**Comment by madanadit** [comment]
@calvinjia Yes, these issues are still present. We should prioritize these.
