### ISSUE TITLE
Architecture and Data Flow

### ISSUE THREAD

**Issue by lord-i-will** [Alluxio/alluxio#10437]
**Page**
https://docs.alluxio.io/os/user/stable/en/Architecture-DataFlow.html#local-cache-hit

**Summary**
As for these words: "For example, if an application requests data access through the Alluxio client, the client asks the Alluxio master for the worker location of the data. If the data is locally available, the Alluxio client uses a “short-circuit” read to bypass the Alluxio worker and read the file directly via the local file system. "

What does "If the data is locally available" mean? Means that the client has read the data once before? Where does the "local data" come from?

**Comment by lord-i-will** [comment]
In the next section, i see the "local worker". Why is the application deployed with a worker? In the production env, alluxio clusters must be deployed on seperated machines. So my application and the worker can not be on the same machine, in this situation how to understand the "Local cache hit" section?

**Comment by ZacBlanco** [comment]
> What does "If the data is locally available" mean? Means that the client has read the data once before? Where does the "local data" come from?

Data locally available means that the data the client is requesting is available on the same physical machine that the client is executing on. This usually means that the Alluxio client application and Alluxio worker process are running on the same machine.

----

> In the next section, i see the "local worker". Why is the application deployed with a worker? In the production env, alluxio clusters must be deployed on seperated machines. So my application and the worker can not be on the same machine, in this situation how to understand the "Local cache hit" section?

It is recommended when deploying Alluxio that your client applications run on the same machine as your Alluxio workers. This provides the most desirable performance characteristics for your applications due to the ability to perform short-circuit reads and avoid network traffic.

If your Alluxio cluster is separated from your applications, then there will never be a local cache hit (i.e. short-circuit) read. Essentially, you will always get a remote hit, and read data over the network.

Hope this helps!

**Comment by lord-i-will** [comment]
thx, @ZacBlanco . Still can not understand "bypass the Alluxio worker and read the file directly via the local file system", "local file system" means the disk? But the following picture use RAM, RAM means memory, right? If "local file system" means the disk, when other clients on different machines request the same data, this worker will read the file again from the disk and cache it. Under this situation, if the local client does not bypass the local worker or the local client cache it in the local worker memory after short-circuit access, it will be smarter, right?

**Comment by ZacBlanco** [comment]
> "local file system" means the disk?

The term "local filesystem" is ambiguous. Generally it means reading from whatever path you've configured your worker storage. This could be:

(note the paths i.e. `/mnt/**` are arbitrary. They could be any value)

- A path such as `/mnt/ssd` which might be mount solid-state or NVMe storage
- A path such as `/mnt/hdd` which might be mount a spinning-disk harddrive
- A path such as `/mnt/ramdisk` which might point to a location in the filesystem mounted as a [ramfs](https://www.kernel.org/doc/Documentation/filesystems/ramfs-rootfs-initramfs.txt)

When an Alluxio client application determines that it is on the same machine as the worker, then the worker will tell the client application where the blocks can be found in the local filesystem (i.e. `/mnt/ramdisk/alluxioworker/blocks/xxxxxxx`). Then the application will read directly from the ramdisk on the local system. This is how we achieve "memory speed" because the filesystem where the block is stored is backed by RAM. Bypassing the worker means we don't need to make RPCs to stream data through the worker process and through the hosts loopback interface. It can be read directly from the filesystem.

> But the following picture use RAM, RAM means memory, right?

It means memory, typically in the form of ramfs or tmpfs. See the link to ramfs kernel documentation above.

>  When other clients on different machines request the same data, this worker will read the file again from the disk and cache it. 

Again "reading from disk" typically will mean ramdisk or whatever storage you have configured for your worker. This means for a "remote cache hit" the client application will need to make an RPC to the remote worker. The worker will read the data from the ramfs, and stream it over the network to the client application.

>  Under this situation, if the local client does not bypass the local worker or the local client cache it in the local worker memory after short-circuit access, it will be smarter, right?

The second half of this sentence is confusing. Can you try to clarify your question

**Comment by ZacBlanco** [comment]
Other than our architecture guide there really is no documentation for how the internals of the system are arranged.

If you're really interested in understanding the inner system, then I can point to a few good files to look at first

- DefaultFileSystemMaster.java
- BaseFileSystem.java
- DefaultBlockWorker.java

Those are the entry points for the main logic of the system - master, client, and worker respectively. If your original question is solved may I close the issue?

**Comment by lord-i-will** [comment]
very thx~ @ZacBlanco
