### ISSUE TITLE
Metadata sync between Alluxio and GCS

### ISSUE THREAD

**Issue by roderickyao** [Alluxio/alluxio#10453]
Today, Alluxio did not implement sync with GCS. It is not straight forward to get changes from the GCS side to show up in Alluxio. In order to get more GCP users to find Alluxio as a good solution for them, syncing data is a fundamental feature to have.

**Comment by dborkar** [comment]
You can configure the property - alluxio.user.file.metadata.sync.interval=<in secs> in the alliuxio site.properties. Any time a file or directory is access, Alluxio will check the understore if it has been more than the time specified by this property. So if you configure it for 7200 = 2 hrs, and issue an alluxio fs ls command, if the 2 hrs are passed since the last check in UFS, Alluxio will go to UFS and get the new metadata for that file or dir.

You can use it from Cli also by giving this property: 
./bin/alluxio fs ls -R -Dalluxio.user.file.metadata.sync.interval=7200 /test

**Comment by yuzhu** [comment]
today alluxio does sync with GCS
