### ISSUE TITLE
flink on alluxio execute wordcount show Failed to cache(Permission denied)

### ISSUE THREAD

**Issue by jinhang** [Alluxio/alluxio#10582]
**Alluxio Version:**
2.0.1
**Describe the bug**
flink on alluxio , execute command:
fink run -m yarn-cluster example/batch/wordcount.jar --input alluxio://{host-name}/test/testFile
--output alluxio://{host-name}/test/outFile
err:
caused by : java .io.IOException: Failed to cache : {alluxio.worker.tieredstore.level0.dirs.path}/alluxioworker/.tmp_blocks/310/3423542352-3f3f3f1324343 (Permission denied)

**To Reproduce**
fink execute wordcount job
**Expected behavior**
fink can write data to alluxio,but now fink only can read data from alluxio
**Urgency**
flink can not work
**Additional context**

**Comment by jinhang** [comment]
we have execute chmod 777 {alluxio.worker.tieredstore.level0.dirs.path}

**Comment by jinhang** [comment]
we execute fink run -m yarn-cluster example/batch/wordcount.jar --input alluxio://{host-name}/test/testFile is running well

**Comment by jinhang** [comment]
someone help me?

**Comment by ZacBlanco** [comment]
@jinhang it will depend upon how your yarn cluster is configured and which nodes your job is scheduled on. Are you in a single node or multi-node setup? have you executed `chmod 777 <alluxio.worker.tieredstore.level0.dirs.path>` on every single worker?

**Comment by jinhang** [comment]
> @jinhang it will depend upon how your yarn cluster is configured and which nodes your job is scheduled on. Are you in a single node or multi-node setup? have you executed `chmod 777 <alluxio.worker.tieredstore.level0.dirs.path>` on every single worker?

yes, I have executed chmod 777 for <alluxio.worker.tieredstore.level0.dirs.path>

**Comment by ZacBlanco** [comment]
But have you done it on every node in the cluster?

Additionally, you can alleviate this by either disabling short-circuit writes (`alluxio.user.short.circuit.enabled=false`) or by [enabling domain sockets](https://docs.alluxio.io/ee/user/stable/en/deploy/Running-Alluxio-On-Docker.html#enable-short-circuit-reads-and-writes). Following either of those two suggestions should alleviate the error you're seeing, but might cause a slight performance hit.

Otherwise, I'll need more information about your cluster configuration. If you have multiple nodes in your cluster, you'll need to `chmod` the worker's data folder on every node, for all configured Alluxio worker tiers.

**Comment by jja725** [comment]
Will close it for now, feel free to reopen it and contact us if this is still valid
