### ISSUE TITLE
Docker without ssh installed

### ISSUE THREAD

**Issue by mauromussin** [Alluxio/alluxio#10586]
**Alluxio Version:**
2.1.0

**Describe the bug**
Alluxio start and stop commands do not work inside the container

**To Reproduce**
executing the command inside the master node
```
bash-4.4$ ./bin/alluxio-stop.sh all
Executing the following command on all master nodes and logging to /opt/alluxio-2.1.0/logs/task.log: /opt/alluxio-2.1.0/bin/alluxio-stop.sh master
Waiting for tasks to finish...
Task on 'localhost' fails, exit code: 127
There are task failures, look at /opt/alluxio-2.1.0/logs/task.log for details.
```
the log file is
```
Executing the following command on all master nodes and logging to /opt/alluxio-2.1.0/logs/task.log: /opt/alluxio-2.1.0/bin/alluxio-stop.sh proxy
[localhost] Connecting as ...
[2019-12-06 14:53:52][localhost] nohup: can't execute 'ssh': No such file or directory
Executing the following command on all worker nodes and logging to /opt/alluxio-2.1.0/logs/task.log: /opt/alluxio-2.1.0/bin/alluxio-stop.sh proxy
[localhost] Connecting as ...
[2019-12-06 14:53:52][localhost] nohup: can't execute 'ssh': No such file or directory
Executing the following command on all worker nodes and logging to /opt/alluxio-2.1.0/logs/task.log: /opt/alluxio-2.1.0/bin/alluxio-stop.sh job_worker
[localhost] Connecting as ...
[2019-12-06 14:53:52][localhost] nohup: can't execute 'ssh': No such file or directory
Executing the following command on all worker nodes and logging to /opt/alluxio-2.1.0/logs/task.log: /opt/alluxio-2.1.0/bin/alluxio-stop.sh worker
[localhost] Connecting as ...
[2019-12-06 14:53:52][localhost] nohup: can't execute 'ssh': No such file or directory
Executing the following command on all master nodes and logging to /opt/alluxio-2.1.0/logs/task.log: /opt/alluxio-2.1.0/bin/alluxio-stop.sh job_master
[localhost] Connecting as ...
[2019-12-06 14:53:54][localhost] nohup: can't execute 'ssh': No such file or directory
Executing the following command on all master nodes and logging to /opt/alluxio-2.1.0/logs/task.log: /opt/alluxio-2.1.0/bin/alluxio-stop.sh master
[localhost] Connecting as ...
[2019-12-06 14:53:56][localhost] nohup: can't execute 'ssh': No such file or directory
```
**Expected behavior**
start & stop smooth

**Urgency**
urgent: the docker microservice could not change config

**Additional context**
Could be an error in the dockerfile (installing without ssh package)

**Comment by ZacBlanco** [comment]
Thanks for reporting this @mauromussin .

I would not label this as a bug. It is expected behavior for the docker container(s).

If you want to change the configuration, you should stop, remove, and then start a new docker container with the proper configuration parameters. Doing otherwise violates the intended design principles for docker.

If you really want to restart the service within the container, then the only way that it is expected to work is if you use one of the start script options that doesn't utilize `ssh`.

this means you would need to `ssh` into each container and issue a `./bin/alluxio-start.sh [master|worker|job_master|job_worker]` depending on the container.

**Comment by ZacBlanco** [comment]
I'm closing this issue as there's been no response in the last week. @mauromussin please re-open if you think this is a real bug.
