### ISSUE TITLE
java client exception : The URI authority ip:19998 does not match the configured value of *****.***.***:19998

### ISSUE THREAD

**Issue by jinhang** [Alluxio/alluxio#10661]
**Alluxio Version:**
What version of Alluxio are you using?
2.1.0
**Describe the bug**
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.IllegalArgumentException: The URI authority **.**.**.**:** does not match the configured value of **.**.**.**:**.
	at alluxio.client.file.BaseFileSystem.checkUri(BaseFileSystem.java:583)
	at alluxio.client.file.BaseFileSystem.openFile(BaseFileSystem.java:410)
	at alluxio.client.file.BaseFileSystem.openFile(BaseFileSystem.java:404)
	at com.huawei.alluxio.Main.main(Main.java:27)
**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)
public class Main {

    public static void main(String[] args) {
        AlluxioURI path = new AlluxioURI("alluxio://****:*****/*****/u.user");
        try {
            InstancedConfiguration conf = InstancedConfiguration.defaults();
            conf.set(PropertyKey.SECURITY_LOGIN_USERNAME, "omm");
            //OpenFilePOptions.newBuilder().setReadType(ReadPType.CACHE);
            FileSystem fs = FileSystem.Factory.create(conf);
            FileInStream in = fs.openFile(path);
            String content = IOUtils.toString(in, "utf-8");
            System.out.println(content);
            in.close();
        } catch (IOException e) {
            e.printStackTrace();
        } catch (AlluxioException e) {
            e.printStackTrace();
        }

    }
}
**Expected behavior**

**Urgency**
Describe the impact and urgency of the bug.
high
**Additional context**

**Comment by jinhang** [comment]
why not remove this condition? 
```
if (uri.hasAuthority()) {
                LOG.warn("The URI authority (hostname and port) is ignored and not required in URIs passed to the Alluxio Filesystem client.");
                Authority configured = alluxio.master.MasterInquireClient.Factory.create(this.mFsContext.getClusterConf(), this.mFsContext.getClientContext().getUserState()).getConnectDetails().toAuthority();
                if (!configured.equals(uri.getAuthority())) {
                    throw new IllegalArgumentException(String.format("The URI authority %s does not match the configured value of %s.", uri.getAuthority(), configured));
                }
            }



```

**Comment by ZacBlanco** [comment]
hi @jinhang  - this occurs when you have an `alluxio-site.properties` file that specifies a different Alluxio master than what is currently configured for the system.

Are you running two different Alluxio clusters? Is there a reason that you need a single client application to connect to both?

additionally, based on your code snippet you can add the line

```java
InstancedConfiguration conf = InstancedConfiguration.defaults();
conf.set(PropertyKey.SECURITY_LOGIN_USERNAME, "omm");
conf.set(PropertyKey.ALLUXIO_MASTER_HOSTNAME, "<desired_host>"
```

And the warnings should go away.


The reason that we have this check in place is because previously when users wanted to connect to one or more clusters, it was confusing if the configuration specified a master host something other than what was in the URI. Which should be respected in that case; the configuration file or the URI? Asking many people we found there were disagreements among which option was the more intuitive.

We could have defined this behavior, but we opted instead to disallow connecting to a cluster which contradicts with the configuration. This ensures that users will always connect to the desired cluster.

**Comment by jinhang** [comment]
@ZacBlanco Thanks,I think you are right.

**Comment by ZacBlanco** [comment]
Please re-open if you feel there is still a bug to be resolved, thanks!
