### ISSUE TITLE
Ability to have a sink connector between a message broker (Like Kafka) and Alluxio S3 API

### ISSUE THREAD

**Issue by Hmr-ramzi** [Alluxio/alluxio#10786]
**Summary**
Lots of message brokers provide connectors to sink topics with other ends (Like Alluxio). The connector creates a way to connect both entities. For example Kafka has a S3 Sink connector to publish data from a topic to the connector. However, i noticed that the REST API for Alluxio S3 is different the AWS S3 REST API and even the alluxio REST API does not support  all the S3 API functionalities. My question so far not to make it long is. Is there a way to connect a message broker (opensource) to Alluxio through the S3 API or i have to implement such connector myself to understand how to call the custom Alluxio S3 API

**Urgency**
Nothing to rush

**Comment by ZacBlanco** [comment]
I am not sure which distribution of Kafka you are using, but if you are trying to write to Alluxio I think the best connector to use would be an HDFS connector - like this one: https://docs.confluent.io/current/connect/kafka-connect-hdfs/index.html

In order to get this working you'll probably just need to put the Alluxio client jar on the classpath of whatever Kafka process actually performs the writes through the connector, then set the `hdfs.uri` to `alluxio://master_hostname:19998/path/to/sink`

I haven't checked the code for their hdfs connector, but if implemented properly it should work.
