### ISSUE TITLE
Alluxio on Docker failed to format journal

### ISSUE THREAD

**Issue by jiacheliu3** [Alluxio/alluxio#10945]
**Alluxio Version:**
2.2.0-SNAPSHOT

**Describe the bug**

There's no ssh command in Alluxio docker image. When doing `formatJournal` in HA mode the command will fail.

```
$ kubectl exec -it alluxio-master-0 bash
bash-4.4$ ssh
bash: ssh: command not found
bash-4.4$ bin/alluxio formatMasters
Executing the following command on all master nodes and logging to /opt/alluxio-2.2.0-SNAPSHOT/logs/task.log: /opt/alluxio-2.2.0-SNAPSHOT/bin/alluxio formatJournal
Waiting for tasks to finish...
Task on 'localhost' fails, exit code: 127
There are task failures, look at /opt/alluxio-2.2.0-SNAPSHOT/logs/task.log for details.
bash-4.4$ cat logs/task.log 
Executing the following command on all master nodes and logging to /opt/alluxio-2.2.0-SNAPSHOT/logs/task.log: /opt/alluxio-2.2.0-SNAPSHOT/bin/alluxio formatJournal
[localhost] Connecting as ...
[2020-02-19 15:03:16][localhost] nohup: can't execute 'ssh': No such file or directory
```

**To Reproduce**
As above

**Expected behavior**
`formatJournal` should work from masters/workers and client side too(if client side is configured).

**Urgency**
Medium

**Additional context**

**Comment by jiacheliu3** [comment]
@ZacBlanco How much overhead is adding `ssh` to our docker image?

**Comment by ZacBlanco** [comment]
The general idea is you should not really be executing commands within the container. Format is an odd one - but generally no, we shouldn't have ssh installed because it would imply all of the other containers have an ssh server running which is another daemon that would need to run in the background.


For k8s or docker its expected for users to run the commands manually at this point

**Comment by jiacheliu3** [comment]
This has been addressed
