### ISSUE TITLE
Prompt "Cannot connect to master [Address]" when client failed to connect to Master

### ISSUE THREAD

**Issue by apc999** [Alluxio/alluxio#11197]
**Is your feature request related to a problem? Please describe.**

```console
$ ./bin/alluxio fs mount /mnt/s3 s3://analytics-zoo-data
Failed to connect to FileSystemMasterClient @ localhost:19998 after 8 attempts
```
The error message is not very clear what happened without hint for users further investigate the root cause.

**Describe the solution you'd like**

Something like:

```console
$ ./bin/alluxio fs mount /mnt/s3 s3://analytics-zoo-data
Failed to connect to Alluxio master (localhost:19998) after 8 attempts
Please check if you Alluxio master is currently running on server "localhost".
```

We may even provide more detailed instructions like "log into master running "jps" to see if process "AlluxioMaster" is running, or check master log at ${ALLUXIO_HOME}/logs/master.log"

**Describe alternatives you've considered**
NA

**Urgency**

**Additional context**

**Comment by githezhihao** [comment]
@apc999 hi~,I had the same error here when  i use presto to execute a query through alluxio.
the presto server log is following:
`io.prestosql.spi.PrestoException: Error opening Hive split alluxio:/beh001/yarn/warehouse/alx_yarn.db/store_sales/000094_0 (offset=100663296, length=33554432): Failed to connect to FileSystemMasterClient @ bonc-bdc-11.bonc.com:19998 after 44 attempts
Caused by: alluxio.exception.status.UnavailableException: Failed to connect to FileSystemMasterClient @ bonc-bdc-11.bonc.com:19998 after 44 attempts
Caused by: alluxio.exception.status.UnavailableException: Failed to handshake with master bonc-bdc-11.bonc.com:19998 to load cluster default configuration values: UNAVAILABLE: io exception
Caused by: alluxio.shaded.client.io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
Caused by: alluxio.shaded.client.io.netty.channel.AbstractChannel.AnnotatedConnectException: finishConnect(..) failed: Connection refused: bonc-bdc-11.bonc.com/192.168.27.220:19998
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused`

here is my alluxio configuration :
`
#worker配置
alluxio.worker.ramdisk.size=25GB
alluxio.worker.tieredstore.levels=1
alluxio.worker.tieredstore.level0.alias=MEM
alluxio.worker.tieredstore.level0.dirs.path=/opt/beh/data/disk/alluxio
alluxio.worker.block.heartbeat.interval=30sec
alluxio.worker.keytab.file=/opt/beh/metadata/key/hadoop.keytab
alluxio.worker.principal=hadoop/@BONC.COM
alluxio.worker.network.async.cache.manager.threads.max=64

#master配置
alluxio.master.hostname=bonc-bdc-7.bonc.com
alluxio.master.mount.table.root.ufs=hdfs://beh001/alluxio
alluxio.master.embedded.journal.addresses=bonc-bdc-9.bonc.com:19200,bonc-bdc-7.bonc.com:19200,bonc-bdc-8.bonc.com:19200
alluxio.underfs.hdfs.configuration=/opt/beh/core/hadoop/etc/hadoop/core-site.xml:/opt/beh/core/hadoop/etc/hadoop/hdfs-site.xml
alluxio.master.keytab.file=/opt/beh/metadata/key/hadoop.keytab
alluxio.master.principal=hadoop/@BONC.COM

# 防止磁盘抖动
alluxio.user.file.passive.cache.enabled=false

# 为Presto增加线程池并发量
alluxio.user.block.master.client.pool.max=256
alluxio.user.file.master.client.pool.size.max=256

# 返回块的完整列表 
alluxio.user.ufs.block.location.all.fallback.enabled=true 

#客户端配置
alluxio.user.hostname=bonc-bdc-5.bonc.com,bonc-bdc-6.bonc.com,bonc-bdc-7.bonc.com,bonc-bdc-8.bonc.com,bonc-bdc-9.bonc.com,bonc-bdc-10.bonc.com,bonc-bdc-11.bonc.com,bonc-bdc-12.bonc.com,bonc-bdc-13.bonc.com,bonc-bdc-14.bonc.com

#alluxio的元数据缓存，用于提高处理小文件速度
alluxio.user.metadata.cache.enabled=true 
alluxio.user.metadata.cache.max.size=100000
alluxio.user.metadata.cache.expiration.time=10min 

#用户读写配置
alluxio.user.file.writetype.default=ASYNC_THROUGH
alluxio.user.file.readtype.default=CACHE_PROMOTE
alluxio.user.file.persistence.initial.wait.time=-1
alluxio.user.file.persist.on.rename=true
alluxio.user.file.replication.durable=1
#alluxio.master.persistence.blacklist=_temporary,.staging,.tmp
alluxio.user.ufs.block.read.location.policy=alluxio.client.block.policy.DeterministicHashPolicy
alluxio.user.ufs.block.read.location.policy.deterministic.hash.shards=1
alluxio.user.metrics.collection.enabled=true
alluxio.locality.compare.node.ip=true
`

i seems like the alluxio client  is looking for  bonc-bdc-11.bonc.com:19998 to handshake, but the host bonc-bdc-11.bonc.com is not my configured masters, it is a work node . 
so  is it a bug in alluxio.client or my configuration has anything unproperly.
Any help you can provide would be greatly appreciated!
