### ISSUE TITLE
Failed to execute any maven operation to Alluxio

### ISSUE THREAD

**Issue by justKidrauhl** [Alluxio/alluxio#11195]
**Alluxio Version:**
What version of Alluxio are you using?
v2.1
**Describe the bug**
Failed to execute any maven operations on Windows.

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)
I'm using Intellij IDEA2019.3.3 and Maven 3.6.3 on Win10.
I tried to run "maven clean" but failed. The error info is "Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.4.0:exec"
I found out there's a linux instruction "rm".

**Expected behavior**
I checked out Alluxio's website and found this:
![image](https://user-images.githubusercontent.com/28786663/77153465-c4778680-6ad4-11ea-8d00-348b208b7f6b.png)
So **I want to know if Alluxio could be build with maven on Windows and run on Linux.**
**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by justKidrauhl** [comment]
If it's feasible to build alluxio on Windows, I also want to know how to fix the problem：
"Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.4.0:exec".

**Comment by ZacBlanco** [comment]
Hi @justKidrauhl, Alluxio does not currently support any windows platforms. You'll need to build and run Alluxio on a Linux or MacOS-based operating system.

Another option which you can try (but is not supported), is to compile directly through the command line using [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10)

You can also try using VirtualBox to launch a CentOS/Ubuntu VM which you can then install IntelliJ and maven on.

Hope this helps. I'm closing this issue because we don't support windows, and I don't think that we will. If you still have issues compiling on other platforms you can re-open this issue
