### ISSUE TITLE
Resilient write streaming

### ISSUE THREAD

**Issue by ggezer** [Alluxio/alluxio#11711]
**Is your feature request related to a problem? Please describe.**
Writing a file to Alluxio is not resilient against worker losses mid-streaming.

**Describe the solution you'd like**
Writing a file should hold on to an entire block buffer until it is properly written to a cache space.
`AlluxioFileOutStream` can take data-stream replication responsibility from `BlockOutStream` and uses the held buffers to replay write for a replacement worker in case of mid-streaming failures.

**Describe alternatives you've considered**
Holding to the full block might make memory pressure in write-heavy workloads.
However, holding on the full block is inevitable because the worker-side block store does not allow chunk/page level commits.

**Urgency**
Writes are getting lost in environments that experience worker unavailability due to overload.

**Comment by ZacBlanco** [comment]
I think this issue is more nuanced once you start considering more of the underlying features Alluxio provides over some of the UFSes. Alluxio has the concept of `WriteType` which has `THROUGH` and `CACHE_THROUGH` types.

For these, we write files to the UFS via a single stream on the designated worker. If we are to lose that worker, then the file would only ever be half complete. UFSes currently don't support append operations, so if we are to make writes resilient by retrying on a different worker, we would need to consider how to join data already written to the UFS via the lost worker, data which may have been streamed to the worker and not written to the UFS, and then finally the rest of the data in the file in order to get the `*THROUGH` write types working properly.

**Comment by ggezer** [comment]
Discussion moved to https://github.com/Alluxio/alluxio/issues/14041
