### ISSUE TITLE
Lack of document about consistency.

### ISSUE THREAD

**Issue by Renkai** [Alluxio/alluxio#11987]
**Page**
https://www.alluxio.io/blog/4-different-ways-to-write-to-alluxio/

**Summary**

A main different between HDFS and S3 is consistency, this blog mentioned it, but details are lack. I hope in the summary table, there could be a column `Consistency` just like `Write Speed` and `Fault Tolerance`.

What I especially want to know is, what consistency Alluxio gives when under storage is S3, and `Write Type` is one of `MUST_CACHE`,`THROUGH`,`CACHE_THROUGH`,`ASYNC_THROUGH`, and what will happen when a worker crashes.

**Comment by ZacBlanco** [comment]
Hi @Renkai. These are good questions to be asking. Generally, Alluxio holds a consistent view of all **metadata** as long as every operation goes through Alluxio.

If you are writing with `MUST_CACHE`, `CACHE_THROUGH` or `ASYNC_THROUGH` the data will be consistent with the metadata as long as the data isn't erased in Alluxio _and_ that the data isn't modified in the underlying storage system through some other means.

Writing with `THROUGH`, Alluxio's metadata about the file will be consistent with what is written, but when reading, the data may not be able to be retrieved and is dependent upon the UFS consistency guarantees.

However, if you introduce modifications to your underlying UFS without using Alluxio, then things get somewhat murkier. Metadata consistency is going to be determined by how often Alluxio is configured to [sync metadata with a UFS](https://docs.alluxio.io/ee/user/stable/en/core-services/Unified-Namespace.html#ufs-metadata-sync) via the property `alluxio.user.file.metadata.sync.interval`. This can be set to something like `1min`, `5min`, `12h`, etc. And so that interval will determine how consistent the master's view of a part of the namespace is.

Do note that that is a client-side property, so you can force a metadata update by setting `alluxio.user.file.metadata.sync.interval=0` (There will be a performance penalty).

Workers crashing do not mean much other than possibly imposing a slight performance hit depending on the data it stored. Since the data is expected to be stored in another underlying system (S3, HDFS, etc) the worker will lose its cached data, but the expectation is that the data is still available. A client will simply look to the next available worker to retrieve the data. If there are no workers with the data, it will pick a worker close to the client and stream the data from the worker, which streams the data from the UFS.

I hope these explanation helps answer your questions.

**Comment by Renkai** [comment]
Hi @ZacBlanco , I still have a question that what will happen if I writing with `ASYNC_THROUGH` and worker crashes after it tell client write success and before it write files to underlying storage.

**Comment by ZacBlanco** [comment]
Sure thing I can clarify that part.

If you are writing with `ASYNC_THROUGH` and the worker crashes before you persist the data, then you will incur a data loss. However, we do provide a feature we call "durable writes" which will split the write among 1 or more workers simultaneously during the write. This prevents data loss in the case of one or more machines. You can enable durable writes by setting the property ` alluxio.user.file.replication.durable`. By default it is one, but if you want to ensure the availability of data in the case of a node loss, you may increase this to 2, 3, or more to produce replicas synchronously during the write.

**Comment by magicsilence** [comment]
> Sure thing I can clarify that part.
> 
> If you are writing with `ASYNC_THROUGH` and the worker crashes before you persist the data, then you will incur a data loss. However, we do provide a feature we call "durable writes" which will split the write among 1 or more workers simultaneously during the write. This prevents data loss in the case of one or more machines. You can enable durable writes by setting the property ` alluxio.user.file.replication.durable`. By default it is one, but if you want to ensure the availability of data in the case of a node loss, you may increase this to 2, 3, or more to produce replicas synchronously during the write.

Would "durable writes"  lead multi writes same data to UFS ?

**Comment by ZacBlanco** [comment]
No, the data will only be written to the UFS once

**Comment by ZacBlanco** [comment]
@Renkai we have most of our documentation at docs.alluxio.io. I think this information is valuable if it is not already included there. Where do you think is the most intuitive place for this information to live there?

**Comment by Renkai** [comment]
@ZacBlanco I think [Apache Flink](https://ci.apache.org/projects/flink/flink-docs-release-1.11/) have a good document hierarchy, especially there are two segments called `concepts` and `internals`, they are very useful for experienced engineers to have a quick understand for a new system.

**Comment by apc999** [comment]
@Renkai  a section on data consistency has been added to `Architecture` page in documentation. https://github.com/Alluxio/alluxio/blob/bc5929e4fd22d4fc2041c7e372ec30f19906ff84/docs/en/overview/Architecture.md
