### ISSUE TITLE
Alluxio and K8s have different interpretation of size

### ISSUE THREAD

**Issue by jiacheliu3** [Alluxio/alluxio#12277]
**Alluxio Version:**
2.4

**Describe the bug**
In K8s context, `g` or `GB` means `1000^3` and `gi` or `GiB` means `1024^3`.
https://stackoverflow.com/questions/50804915/kubernetes-size-definitions-whats-the-difference-of-gi-and-g

In Alluxio context, `g` or `GB` means `1024^3`.
https://github.com/Alluxio/alluxio/blob/a5265484f6f0cfcb7745dec31e61030056b49240/core/base/src/main/java/alluxio/Constants.java#L23

So when we use `g` and pass the quota to Alluxio and K8s, K8s grants `1000^3` but Alluxio tries to utilize `1024^3`. For example if it is an `emptyDir`, then the pod using the `emptyDir` will be killed for overusing resources.

**To Reproduce**
Steps to reproduce the behavior (as minimally and precisely as possible)

**Expected behavior**
Alluxio and K8s should have consistent understanding about sizes, especially they are parsing the same piece of configuration field.

**Urgency**
Describe the impact and urgency of the bug.

**Additional context**

**Comment by jiacheliu3** [comment]
There are a few options:
1. Workaround: Use bytes all across the helm chart configuration to avoid conversion. This can only be a workaround as users will face the issue when they use expressions like `4G`.

1. Change Alluxio conversion to be `G = 1000^3` and `Gi = 1024^3`. This breaks the backward compatibility but will guarantee consistent (and correct?) behavior.

1. Change Alluxio conversion to be `G = Gi = 1024 ^ 3`. This gives backward compatibility but might be a confusing fix.

**Comment by jiacheliu3** [comment]
@madanadit What do you think about this?

**Comment by madanadit** [comment]
@jiacheliu3 I would suggest:
1. Alluxio helm chart uses the K8s convention (G = 1000^3) (for comformity)
2. We do not change the convention for Alluxio servers either (for backwards compatibility)
3. When we set a helm config to X G, we transform the value to bytes and set Alluxio config in B. Similar for other units as well.

**Comment by jiacheliu3** [comment]
> @jiacheliu3 I would suggest:
> 
> 1. Alluxio helm chart uses the K8s convention (G = 1000^3) (for comformity)
> 2. We do not change the convention for Alluxio servers either (for backwards compatibility)
> 3. When we set a helm config in G or Gi, we transform the value to bytes and set Alluxio config in B. Similar for other units as well.

This will only work for helm chart right? When the user tries to use `kubectl` and manually give `G` to both K8s and Alluxio, there will still be a confusing resource mismatch.

**Comment by ZhuTopher** [comment]
@madanadit @jiacheliu3 Since this issue seems to be popping up again and again, let's revive this discussion.

As Jiacheng mentioned there will be no way to ensure correct behaviour across all k8s tools (present and future) unless this is addressed properly. If we are not willing to break backwards compatibility in Alluxio (which is understandable), we can make it an opt-in rolling upgrade to enable the distinction in Alluxio between `Gi` and `G` and at some point in the future (e.g 3.0.0) we make it a fully committed change.

If this solution is undesirable then the only option we are left with is to concede that K8s and Alluxio have mismatching interpretations of G and document this extensively with corresponding workarounds.
- 1 `GiB` ~= 1.074 `GB`, or conversely 0.931 `GiB` <= 1 `GB`
- Therefore we document that any Alluxio worker cache capacity backed by a k8s volume specified using `GB` require a high watermark <= 0.931

**Comment by ZhuTopher** [comment]
Discussed wth @madanadit, here's a compromise that should be minimally impactful:
1. Add the `KiB`/`MiB`/`GiB`/`TiB` suffix to Alluxio's parsing and map them to be identical to the existing `KB`/`MB`/`GB`/`TB` mappings.
2. Specify that all users of the Alluxio in a K8s environment (Helm or otherwise) should use the 2-bit based notation for any storage sizes, as this is the _only_ interpretation Alluxio supports.

This requires zero end-user changes for normal Alluxio deployments, and a small change to our Helm chart & corresponding documentation. Otherwise, if end users attempt to use the base-10 notation in k8s with Alluxio it is at their own risk.

**Comment by ZhuTopher** [comment]
In the meantime, this error and its observed symptom(s) should be added to the troubleshooting section of [the Alluxio K8s doc page](https://docs.alluxio.io/os/user/stable/en/deploy/Running-Alluxio-On-Kubernetes.html#troubleshooting)

Ex:
```
tmpfs is smaller than the configured size: tmpfs size: 500002816, configured size: 524288000
```

This occurs because the K8s interprets the `sizeLimit: 5G` of the `emptyDir` volume as 5*1000^3 bytes whereas the binary tool `tmpfs` used in the [alluxio-mount.sh]() interprets G as Gi => 5*1024^3 bytes.

There is currently no workaround for this.
