### ISSUE TITLE
can alluxio change default ttlaction from delete to free?

### ISSUE THREAD

**Issue by jiemar** [Alluxio/alluxio#12316]
**Alluxio Version:
2.3

it is very dangerous for ttlaction default to be delete. ufs file may be deleted

**Comment by apc999** [comment]
@calvinjia @gpang  do you remember the reason in early days we set default to delete for ttlaction after ttl expires?
I agree with @jiemar  that deleting files from UFS as default ttl action is risky.

**Comment by apc999** [comment]
In https://github.com/Alluxio/alluxio/blob/e5d4ea2e59993a9c47dcb08ce7aa0c95b948af84/core/common/src/main/java/alluxio/conf/PropertyKey.java#L3569-L3572 change `DELETE` to `FREE`, @cheyang  do you want to create a patch?

**Comment by calvinjia** [comment]
@jiemar Thanks for raising this issue. The concept of TTL free does not have good semantics, so having it as the default was very confusing to users as well. I think the preferred resolution is to not overload TTL with free/delete modes and attach a bigger warning to using default TTL that is not `-1`. @maobaolong do you mind making the doc change instead of the default value change?

**Comment by maobaolong** [comment]
@calvinjia I'm ok to add `-1 is not the default TTL` into the documents.

**Comment by cheyang** [comment]
> In
> 
> https://github.com/Alluxio/alluxio/blob/e5d4ea2e59993a9c47dcb08ce7aa0c95b948af84/core/common/src/main/java/alluxio/conf/PropertyKey.java#L3569-L3572
> 
> change `DELETE` to `FREE`, @cheyang do you want to create a patch?

Done with https://github.com/Alluxio/alluxio/pull/12443

**Comment by maobaolong** [comment]
@cheyang This seems duplicate to #12390
