### ISSUE TITLE
Document was not updated

### ISSUE THREAD

**Issue by wheatxiong** [Alluxio/alluxio#12736]
**Page**
We had submitted a document pr in https://github.com/Alluxio/alluxio/pull/12693 ，but website is not updated. 

**Summary**
We had submitted a document pr in #12693 ，but website is not updated. As shown below：
![image](https://user-images.githubusercontent.com/10227292/104869827-ebffdf80-5981-11eb-8fb8-2ad181f3f530.png)

On the other hand, Chinese website cannot show more message in Cloud Native .
![image](https://user-images.githubusercontent.com/10227292/104870094-9415a880-5982-11eb-91e1-3ee89d857d46.png)

Do I need to do something to trigger it ?

**Comment by apc999** [comment]
@Xenorith  can you help and let us know where to update?

**Comment by Xenorith** [comment]
the default landing page for documentation uses the version of the most recently released version, which is `v2.4 (stable)`. the PR with the documentation changes will not show up for this version because it was merged into the `master` branch.

the documentation displayed under the `master (edge)` version gets updated when a new edge release occurs. since the last one was `2.4.1-1`, [see release notes here](https://www.alluxio.io/download/releases/alluxio-2-4-1-1-release/), the changes for this PR are not reflected anywhere in docs.alluxio.io at this point.

in order for this change to appear, we would either:
- cherry pick this PR to `branch-2.4`, assuming the documentation is relevant for version 2.4, which would result in the documentation showing up where it was expected as described in the issue
- create a new edge release, `2.4.1-2`, which would result in the documentation showing up under the `master (edge)` version

@apc999 let me know if you need more clarity regarding this situation

**Comment by apc999** [comment]
@Xenorith  thanks for the clarification. I have created https://github.com/Alluxio/alluxio/pull/12738 to cherrypick the PR to 2.4 branch

**Comment by apc999** [comment]
#12738  merged. close this issue. please reopen this issue if it still does not work , @wheatxiong

**Comment by apc999** [comment]
Updated now: https://docs.alluxio.io/os/user/stable/en/cloud/Tencent-Cloud-EMR.html

**Comment by wheatxiong** [comment]
it is cool! thanks a lot for help!
