### ISSUE TITLE
ERROR AlluxioJniFuseFileSystem - File is not completed

### ISSUE THREAD

**Issue by peterroelants** [Alluxio/alluxio#13129]
**Alluxio Version:**
2.5.0-1

**Describe the bug**
After writing a file to an Alluxio FUSE mounted folder I start seeing the following message repeated in the alluxio-fuse logs:
```
ERROR AlluxioJniFuseFileSystem - File /test.txt is not completed
```

When trying to read the file from the folder I get the following local error:
```
$ cat ${MOUNT_POINT}/test.txt
cat: /mnt/fuse_parent_volume/alluxio_fuse/test.txt: Input/output error
```
And see the following in the alluxio-fuse process logs:
```
alluxio.exception.FileIncompleteException: Cannot read from /test.txt because it is incomplete. Wait for the file to be marked as complete by the writing thread or application.
	at alluxio.client.file.BaseFileSystem.openFile(BaseFileSystem.java:395)
	at alluxio.client.file.BaseFileSystem.openFile(BaseFileSystem.java:383)
	at alluxio.client.file.FileSystem.openFile(FileSystem.java:498)
	at alluxio.fuse.AlluxioJniFuseFileSystem.openInternal(AlluxioJniFuseFileSystem.java:330)
	at alluxio.fuse.AlluxioJniFuseFileSystem.lambda$open$4(AlluxioJniFuseFileSystem.java:321)
	at alluxio.fuse.AlluxioFuseUtils.call(AlluxioFuseUtils.java:278)
	at alluxio.fuse.AlluxioJniFuseFileSystem.open(AlluxioJniFuseFileSystem.java:321)
	at alluxio.jnifuse.AbstractFuseFileSystem.openCallback(AbstractFuseFileSystem.java:171)
```
Also `ls ${MOUNT_POINT}` takes much longer than usual, and is in the order of multiple seconds each time.

The weird thing is the file is in Alluxio (from the Master dashboard):
![image](https://user-images.githubusercontent.com/951093/112646602-f76efb80-8e47-11eb-9a7a-77bfbbf00326.png)

**To Reproduce**
- Launch Alluxio Master and Worker
- Launch Alluxio fuse
- Write simple test file to mount point, e.g. `echo "test" > ${MOUNT_POINT}/test.txt`

**Expected behavior**
I expect Alluxio FUSE to work

**Urgency**
High

**Additional context**
- Running in Docker.
- FUSE config:
```
alluxio.fuse.jnifuse.enabled=true
alluxio.user.file.readtype.default=CACHE
alluxio.user.file.writetype.default=ASYNC_THROUGH
alluxio.fuse.maxwrite.bytes=131072
alluxio.fuse.shared.caching.reader.enabled=false
alluxio.user.metadata.cache.enabled=true
```

**Comment by peterroelants** [comment]
Setting `alluxio.user.metadata.cache.enabled=false` seems to resolve the issue

**Comment by apc999** [comment]
@peterroelants thanks for reporting this.
@maobaolong  can you take a look at this issue?

**Comment by maobaolong** [comment]
@apc999 Sure

**Comment by LuQQiu** [comment]
https://github.com/Alluxio/alluxio/pull/13111 Add wait for file completed logics if the file is being written
This PR is included in 2.5.0-1

Basically, we want operations like ls and open file waiting for a being written file to finish its writing and then do the ls and open.
Otherwise, ls may show 0 byte size and cause some tensorflow operation to fail. Open will also show FileIncompleteException if the file is not completed.

We only wait for a file to complete for up to 5sec. I guess the issue comes from: the file is being written - an open() is issued - open() wait for the file to complete for 5 sec, but the file isn't finished writing in this 5 sec - open() throws FileInComplete exception.

The 5sec now is hardcoded and we can make it configurable. 

There could be a bug why the file didn't update its status as complete... I will try on my environment and see if reproduceble

**Comment by LuQQiu** [comment]
@peterroelants Metadata cache should be enabled only in read-only workloads with data/metadata remains unchanged (no file modification through either alluxio or UFS directly). Otherwise AlluxioFuse will cache the wrong metadata and will not go to the Alluxio servers or UFS to fetch the updated metadata information. In your case, AlluxioFuse cached the file metadata which shows that the file is not completed. Even though the metadata is updated in Alluxio servers (when you do ls, you see the correct metadata), AlluxioFuse keeps the old metadata and doesn't update those metadata.

**Comment by peterroelants** [comment]
@LuQQiu Thank you for the clarification, this makes sense.

I will keep `alluxio.user.metadata.cache.enabled=false` whenever writes will occur.

**Comment by apc999** [comment]
@peterroelants  I'm adding a new task https://github.com/Alluxio/alluxio/issues/13186 to help your use case so writes can still use `alluxio.user.metadata.cache.enabled=true`

**Comment by peterroelants** [comment]
@apc999 Thank you.
Just so you know the urgency for me personally became quite low atm since I can get away with `alluxio.user.metadata.cache.enabled=false` most of the time.
