### ISSUE TITLE
claim.Spec.Selector is not supported for dynamic provisioning on AWS

### ISSUE THREAD

**Issue by datYori** [Alluxio/alluxio#13497]
The following

https://github.com/Alluxio/alluxio/blob/e6b7900126ebb8d236410f35ad69b6ffdb258470/integration/kubernetes/helm-chart/alluxio/templates/worker/domain-socket-pvc.yaml#L33-L38

results in 

```K8s dynamic volume provisioning: claim.Spec.Selector is not supported for dynamic provisioning on AWS```

when you go with `gp2` storage class

**Comment by apc999** [comment]
@jiacheliu3 @cheyang  do you have a good understanding of this issue?

**Comment by jiacheliu3** [comment]
@apc999 When the user is using dynamic PV provisioning (instead of manually creating PVs), the dynamic PV provisioners in K8s do NOT support specifying the selectors yet so the provision will fail. The solution will be to change the default selector to empty, same to https://github.com/Alluxio/alluxio/pull/13379 is doing for the logserver PVC.
