### ISSUE TITLE
JMX metrics of alluxio local cache are missing in Presto's JMX connector

### ISSUE THREAD

**Issue by beinan** [Alluxio/alluxio#14200]
**Alluxio Version:**
2.6.1, 2.6.2

**Describe the bug**
JMX metrics of alluxio local cache are missing in Presto's JMX connector.
The values such as bytes_in_cache exposed by JMX are always 0.  But these values are good via jConsole.

**To Reproduce**
1 Start presto with local cache enabled
2 Run some queries
3. Try to query the jmx via the build-in jmx connector in Presto.  

**Expected behavior**
We expect to see accurate (non-zero) values in the JMX metrics

**Urgency**
Normal

**Additional context**
Reported by Zou Fei and Zhang Ce.  Many thanks!

**Comment by rongrong** [comment]
I tried this out with the jmx connector in Presto and I can see data. The caveat is that due to how Alluxio jmx metric keys are constructed, by default it would include the ip address of the node in the metric name. In jmx connector, these names are mapped to table names. For example, run `SHOW TABLES IN jmx.current`, and you will see table names like `com.facebook.alluxio:name=client.cachebytesreadexternal.192_168_0_15,type=meters`. Since different worker would have different ip addresses, this no longer works in aggregate. The way to work around it for now is to overwrite `alluxio.user.app.id`. For example, add `-Dalluxio.user.app.id=test` to runtime configuration will change the metric name to `com.facebook.alluxio:name=client.cachebytesreadexternal.test,type=meters`. This way run `SELECT * from current."com.facebook.alluxio:name=client.cachebytesreadexternal.test,type=meters"` should give all entries from all worker nodes.

**Comment by beinan** [comment]
Hi @FeiZou , I think @rongrong worked out a work around for you.  You could use -Dalluxio.user.app.id=test to override the ip/hostname in the metrics key, then the JMX connector should work as expected.

**Comment by nmahadevuni** [comment]
Thanks for the workaround @rongrong . I'm able to see many counters after using the workaround but "client.cachehitrate" is still missing. I can view this counter using jConsole. But not showing up in jmx.current tables.

**Comment by FeiZou** [comment]
Hey @rongrong for providing the workaround. I have the same doubt as @nmahadevuni that I cannot see the some important metrics like `Client.CacheHitRate` ,`Client.CacheSpaceAvailable` and `Client.CacheSpaceUsed` through JMX.current.

**Comment by nmahadevuni** [comment]
hi @beinan @rongrong : Unless we set the Presto coordinator also as worker(_node-scheduler.include-coordinator=true_), we cannot see counters like Client.CacheHitRate, Client.CacheBytesReadCache, Client.CacheBytesReadExternal, Client.CacheBytesRequestedExternal
Is there any workaround for this?

**Comment by rongrong** [comment]
@FeiZou `Client.CacheSpaceAvailable` and `Client.CacheSpaceUsed` should be available. `CacheHitRate` is missing because it's currently not registered on Presto coordinator. JMX connector would only list the metrics that are visible on coordinator. I'll send out a PR to register cache hit rate on coordinator as well. @nmahadevuni any other metrics missing while I'm at it?

**Comment by rongrong** [comment]
BTW, the fundamental culprit of this is that Presto's JMX connector (and all other connectors pretty much)'s metadata queries are running on coordinator only. Since the JMX metrics are mapped to tables, and table listing is a metadata query, listing tables would only run on coordinator, thus only listing all the metrics that are registered on coordinator. So if caching is not enabled on coordinator, you will not get any cache metrics. In that case, I'd suggest to not rely on jmx connector, but use other jmx monitoring tools.

**Comment by nmahadevuni** [comment]
The ones I mentioned above are the only metrics missing, I found rest of them are registered on coordinator too.
