### ISSUE TITLE
tensorflow training stuck with fuse

### ISSUE THREAD

**Issue by lilyzhoupeijie** [Alluxio/alluxio#14514]
**Alluxio Version:**
alluxio 2.6.1
tensorflow
2.4.0

**Describe the bug**
When training using alluxio,the tensorflow job stuck,and training can't go on anymore，sometimes the tf appears error,sometimes it will just keep and no steps running

**Expected behavior**
The training running normally all the time

**Urgency**
very urgency

**Additional context**
maybe there is some fd leak?
https://www.jianshu.com/p/1f9cff12b84f?utm_source=oschina-app

the stuck tf fd shows:
![unnormal](https://user-images.githubusercontent.com/24890599/141397247-e0ef5730-f84f-43e1-ac14-6887021786cd.png)

the normal tf  using alluxio ,fd shows:
![normal](https://user-images.githubusercontent.com/24890599/141397273-65038f30-e301-4e31-bc2e-e9d570d6f1ad.png)

afte user report error,I enter the tensorflow pod,and the data can be read normally.
the same training job,when read from the other storage,no stuck error.
alluxio cluter with big datas and training  with a lot of data happens more frequently.

**Comment by LuQQiu** [comment]
@LuQQiu will take a look the fd problem
Also we will add Fuse metrics monitoring to know when the tensorflow stuck so that we can know it at the first place and go get more information

**Comment by LuQQiu** [comment]
@lilyzhoupeijie From the graph, the process is not reading files from Alluxio, but it doesn't show any actual errors. If we can catch the moment that the job stuck and get more information there, like some error message, Alluxio jstack , Alluxio Fuse metrics monitoring.

**Comment by apc999** [comment]
highest priority to resolve by @LuQQiu , aiming for next release after 2.7.1

**Comment by LuQQiu** [comment]
The first step of this problem is to know whether tensorflow is stuck on the AlluxioFuse side.
This includes two questions:
Q1: How to know after Alluxio Fuse stuck?
- Fuse thread: fuse operation takes longer than `alluxio.fuse.logging.threshold` will have warning log in fuse.log
- Fuse process: add Fuse process JVM pause monitoring service https://github.com/Alluxio/alluxio/pull/14608
Fuse process JVM pause monitor, for related information https://docs.alluxio.io/os/user/stable/en/operation/Performance-Tuning.html#jvm-monitoring
`alluxio.standalone.fuse.jvm.monitor.enabled=true` (false by default)
When JVM pause, the information is shown in fuse log or fuse process metrics. 
`Server.JvmPauseMonitorTotalExtraTime`
`Server.JvmPauseMonitorWarnTimeExceeded`
`Server.JvmPauseMonitorInfoTimeExceeded`

Q2: How to know when Alluxio Fuse stuck
- Fuse process: when the monitoring service cannot get new metrics from the Fuse process
- Fuse thread: Design: add Thread time exceed metrics. In AlluxioFuse, add a thread time monitoring service. When a libfuse thread enters an operation, the monitoring service log the thread enter time. When the thread finishes an operation, the monitoring service remove the time log. Monitoring service periodically checking how much time all the current threads take. If any is longer than the configured threshold, log to the fuse.log and add counters to the related metrics.

**Comment by lilyzhoupeijie** [comment]
We suspect that fuse cannot read normally, resulting in tensorflow stuck in a strange position

**Comment by LuQQiu** [comment]
@lilyzhoupeijie we add more metrics so that it may help identify the tensorflow fuse stuck easier https://github.com/Alluxio/alluxio/pull/14657

**Comment by LuQQiu** [comment]
Close this issue for now, feel free to reopen it
