### ISSUE TITLE
Copy bunches of small files through posix to s3 ufs is much slower than using cmdlet inside the same pod

### ISSUE THREAD

**Issue by Nizifan** [Alluxio/alluxio#14614]
**Alluxio Version:**
2.5

**Describe the bug**
When copy a folder contains tons of small file to Alluxio, compared with Alluxio cmdlet, the posix interface is 4x time slower. 
We embedded fuse client as sidecar container for the train pod, the posix write is inside the train pod(main container), and do Alluxio cmd write in fuse client(sidecar container).

I try to write a folder to s3 ufs through Alluxio, which consist 3.6k picture of ~15k and 3.6k json whose size << 1k, total size is 69M.
The fuse pod is not in the same machine with the worker machine.

Using Alluxio cmd take ~20s to finish, while using posix interface to copy take ~80s to finish

use another folder, which consist 36k picture of size ~20k and 36k json size << 1k, total size is 853M.
Using Alluxio cmd take 175 seconds to finish, while using posix interface to copy take 572s seconds to finish.

usage of Alluxio cmd:
/opt/alluxio-release-2.5.0-2-SNAPSHOT/bin/alluxio fs copyFromLocal -Dalluxio.user.file.writetype.default=$1 ./hand_cls_p1/dataset_01/ "/test/dataset01_test/$2/" > log.txt
usage of posix interface:
cp -rf ./hand_cls_p1/dataset_01/ "/DATA/jupyter/fluid-test-jssz/test/$1/" <= Alluxio mount point

**To Reproduce**

folder 1 of 69M and 7.2k file:
Posix = 82s:
bili-docker /workspace > bash a.sh test01_1_1
2021-12-02 17:28:44
2021-12-02 17:30:06
cmdlet = 20s:
root@train-4834-worker-0:/workspace# bash a.sh ASYNC_THROUGH test4
2021-12-02 16:00:57
2021-12-02 16:01:17

as benchmark, directly uploading using s3 cli take ~20s, too.

folder 2 of 853M and 72k file:
Posix = 840s
bili-docker /workspace > bash a.sh test01_1_2
2021-12-02 17:30:32
2021-12-02 17:44:32
cmdlet = 186s
oot@train-4834-worker-0:/workspace# bash a.sh ASYNC_THROUGH test2_1
2021-12-02 16:05:28
2021-12-02 16:08:34

as benchmark, directly uploading using s3 cli take ~180s.

**Expected behavior**
We expect posix write to have similar speed compared with Alluxio cmdlet write. The 3.5x time cost will stop user from using Alluxio cache which is much slower compared to directly upload to s3.

**Urgency**
This is urgent as it is blocking issue for using Alluxio in Production environment.

**Comment by Nizifan** [comment]
[alluxioconfig.txt](https://github.com/Alluxio/alluxio/files/7640825/alluxioconfig.txt)
config using GetConf

**Comment by LuQQiu** [comment]
Tested with a single machine with colocated worker and fuse with SSD
MUST_CACHE/ASYNC_THROUGH has similar performance

WorkerFuse or StandaloneFuse
```
$ time cp -R ~/testFiles /mnt/alluxio-worker-fuse/testFiles
real	0m45.662s
```

Alluxio commandline
```
time bin/alluxio fs copyFromLocal  -Dalluxio.user.file.writetype.default=MUST_CACHE ~/testFiles/ /testFiles
real	0m7.316s
```

S3 CLI
```
aws s3 cp --recursive ~/testFiles/ s3://XXX/testFiles
real	0m37.282s
```

Working on improving Fuse to have similar performance compared to Alluxio commandline.

**Comment by LuQQiu** [comment]
The performance investigation conclusion: 
Fuse (7 seconds) copy the same directories from local filesystem to Alluxio is around 6 times slower than copyFromLocal command (45 seconds).
In my investigation, I found that on the Fuse side, there are **three to five threads** executing the copy requests, but on the copyFromLocal side, **32 threads** are executing the copy requests. 
45 / 7 = 6.2 close to 32 / 5 = 6.4.
The biggest reason for the relatively bad performance of copying a large amount of small files comes from **libfuse working thread number**. 

For more details of how i find out it's the Fuse thread number is the main reason of the performance:
1. I try to see if WorkerFuse has the similar performance as the remote standalone Fuse process, since WorkerFuse is easier to get metrics information. Yeah, workerFuse has the similar performance.
2. get the WorkerFuse metrics when running the copy command. 

The critical RPCs for Fuse write paths includes 
Fuse RPCs `Fuse.Create` `Fuse.Getattr` `Fuse.Write` `Fuse.Flush` `Fuse.Release`
Client RPCs `Client/Worker.CreateFile` `Client/Worker.GetNewBlockIdForFile` `Client/Worker.GetStatus` `Client/Worker.CompleteFile`. Those RPCs are issued by client to master. 

They all have timer metrics. By multiplying count and mean we get the total duration. Then we know which operations consume the most time.

By tracing and understanding the `AlluxioJNIFuseFileSystem.create/getattr/write/close`, we can see what RPCs Fuse called.
-CreateFile 17.4 second
---FileSystemMasterClient.createFile 16.64 second
---Created AlluxioFileOutStream
-Write 16.4 second 
---FileSystemMasterClient.getNewBlockIdForFile 16second
---BlockWorkerDataWriter 
-----BlockWorker.createBlock
-----BlockWorker.createBlockWriter
-----BlockWorker.requestSpace
-----BlockWriter.append(buf)
-----CurrentBlockOutStream.write
-Flush
---OutStream.flush
Release 30 second
---All outStream.close()
---Master.completeFile 20.4 second

We can see that most of the time spent in Client RPC operations interacting with Master.
After looking into the CopyFromLocal code, the RPCs they run are nearly the same.

3. Understand copyFromLocal code,  configure the [CVS metrics sink](https://docs.alluxio.io/os/user/stable/en/operation/Metrics-System.html#csv-sink-setup) before running the copyFromLocal command, and get its metrics. 

CopyFromLocal metrics show similar time spent in RPC operations.

4. Alluxio metrics shows that small files write through Alluxio Fuse or CopyFromLocal Alluxio CLI take nearly the same time inside Alluxio. Then my guess is maybe thread number is the cause of the performance differences.

5. By doing jstack and logging, copyFromLocal uses 32 threads while Fuse only uses 3-5 threads to execute the write request which is highly likely the reason why copyFromLocal has much better performance than FUSE.

**Comment by Nizifan** [comment]
Many thanks for @LuQQiu for detailed investigation! The evidence looks really convincing!

Btw, do we have way to improve that part of behavior? I roughly go through the configure and didn't find some related config.

**Comment by LuQQiu** [comment]
Linux cp/dd is single thread cp function which means that it's sequential (cp one after another).
while alluxio copyFromLocal and s3 CLI are both multi-thread application.
So it's not a apple to apple comparison.

Alluxio Fuse stressbench write throughput test is implemented https://github.com/Alluxio/alluxio/issues/14539
One can use something similar to 
```
 bin/alluxio runClass alluxio.stress.cli.fuse.FuseIOBench --local-path /mnt/alluxio-fuse/ --bench-timeout 1h --buffer-size 15KB --cluster-limit 1 --file-size 15KB --num-dirs 36 --num-files-per-dir 100 --operation Write --threads 36 --warmup 5 --duration 30
```
The `warmup` `duration` and test file number may need to be adjusted, one can run `bin/alluxio runClass alluxio.stress.cli.fuse.FuseIOBench` for the usage.
