### ISSUE TITLE
Alluxio worker K8S storage management

### ISSUE THREAD

**Issue by LuQQiu** [Alluxio/alluxio#14616]
**Is your feature request related to a problem? Please describe.*
Alluxio manages the worker storage according to the user-given storage space (e.g. alluxio.worker.tieredstore.level0.dirs.quota).
However in K8S, sometimes the storage space is shared by multiple applications.
K8S may not know the available storage space for Alluxio beforehand so configure a wrong storage size (large than actual).
Or during runtime, the storage space may be used out by other applications. When Alluxio thinks there are 10GB left but there may be only 1GB or none left.

**Describe the solution you'd like**
Alluxio has disk space detection.
Say when Alluxio is configured to have 30GB storage and Alluxio used 10GB. Other applications used 10GB.
Alluxio will know that it has 10GB left and will not fully use out the whole storage space which the whole pod (Alluxio) may be killed by K8S.

**Describe alternatives you've considered**
Users do disk space management outside Alluxio with K8S ways.
It's more complicated that way.

**Urgency**
Important, is a blocking issue

**Additional context**

**Comment by LuQQiu** [comment]
@apc999 @beinan FYI

**Comment by beinan** [comment]
Does this mean that we need to check the available space from time to time at runtime？ Is it possible to use a small and safe quota (say <10GB ) as a workaround?

**Comment by umialpha** [comment]
thanks @LuQQiu  for tracking our issues. 🌹

@beinan 
Disk management is not a major problem on bare metal machine or dedicated servers. However, when it comes to k8s, everything changes. 

We deploy alluxio with [fluid](https://github.com/fluid-cloudnative/fluid)(an alluxio controller responsible for deployment) on k8s shared with multiple applications.  Claiming 10GB is not a good idea because it may be scheduled on a machine with only 1GB disk left.

Our preliminary idea is that alluxio claims the disk usage, k8s-scheduler schedules alluxio workers based on the claim. Then alluxio has to make sure it can't exceed the usage.

Any other ideas are welcome. If there is any roadmap on this issue, pls let us know.

**Comment by LuQQiu** [comment]
@ssz1997 FYI

**Comment by JySongWithZhangCe** [comment]
@LuQQiu Is it possible to reserve 30GB?

**Comment by LuQQiu** [comment]
According to @beinan it's hard for us to know how much storage actually left. We can reserve any number based on Alluxio configuration, but not based on actual storage space

**Comment by beinan** [comment]
Yes, as @LuQQiu mentioned, the quota could not be working based on the actual storage space unless k8s could provide this information.  But even though we know the actual storage when the alluxio starts, other application running on the same machine might still preempt the space during the alluxio running.   I don't have a workaround for this issue so far.

I'm thinking if we could reserve the space during the server start in the future, it sounds like a reasonable feature request to me.

**Comment by umialpha** [comment]
Thanks for your kindly reply. It sounds that it's k8s responsibility for disk management.

**Comment by beinan** [comment]
> Thanks for your kindly reply. It sounds that it's k8s responsibility for disk management.

Yeah, I'm not an expert of k8s, not sure if the disk management has already been there or not.

**Comment by LuQQiu** [comment]
Close because Alluxio cannot know how many disk spaces left
