### ISSUE TITLE
MetricsSystem memory leak

### ISSUE THREAD

**Issue by chovy-3012** [Alluxio/alluxio#14766]
**Alluxio Version:**
2.8.0-SNAPSHOT

**Describe the bug**
We add alluxio jar in hivemetastore classpath.
Hivemetastore crash down ,when we query hive through alluxio.

![image](https://user-images.githubusercontent.com/6967684/147751566-39f94501-423d-4562-9d0c-b73ebe61853b.png)

![image](https://user-images.githubusercontent.com/6967684/147751585-138b164d-7c2e-4db8-89ae-c631de683144.png)

![image](https://user-images.githubusercontent.com/6967684/147801286-30d99473-a5f5-40b7-85b9-bb264bdb7e64.png)
Host-1`G1 Old Gen` is normal, another host `G1 Old Gen` is abnormal .

**Comment by LuQQiu** [comment]
@jiacheliu3 @yuzhu FYI

**Comment by yuzhu** [comment]
@jiacheliu3 can you take a look at this? this seems like a high impact bug.

**Comment by jiacheliu3** [comment]
Hi @chovy-3012 Thanks for reporting this issue. I'm looking at your screenshots and there's some information missing.

![image](https://user-images.githubusercontent.com/14806853/162663160-76b21d02-0b47-4861-a4f1-eb36acd97f0a.png)
In your 1st screenshot, seems the heap is retained by the MetricsSystem instance in the AppClassLoader. However, seeing the AppClassLoader linking to retained heap typically means that memory is held by some Alluxio objects initialized by that class. In order to find the "leak" objects, you will need to dig deeper into that AppClassLoader object in MAT until you see the bottom. Could you find where that 9G are allocated to and attach a screenshot?

![image](https://user-images.githubusercontent.com/14806853/162663564-df75800f-0432-4c21-bb58-9dbc31a1aba8.png)
This one seems to be VisualVM. I can see all those ConcurrentHashMap$Node or Node[] are taking 9G. But the particular object you are looking at in the screenshot is only 2MB, can you find where the 9G are allocated to?
