### ISSUE TITLE
Alluxio master memory is very high, serving 2T data, and stop world gc for several times

### ISSUE THREAD

**Issue by Nizifan** [Alluxio/alluxio#14844]
**Alluxio Version:**
2.7

**Describe the bug**
when serving user with 2T dataset on s3, memory keep at high level, from 37G ~ 63G(limit 64G), the memory go up in 1 hour and then stop world gc happen, cause availability issue.
user dataset is around 2T and consist picture of ~100k, user will iterating reading the picture in parallel.

a typical gc:
![image](https://user-images.githubusercontent.com/11472213/149328133-2cb76bbb-4d17-40ef-840a-32339a854842.png)

**Comment by LuQQiu** [comment]
More than 20 million files for this dataset. @Nizifan can you give some information about the file tree structure? like how many levels of directories are in this dataset, how many files are in each directory? no need to be precise, but used to get a rough idea.

The other behavior mentioned by @Nizifan ,
Case 1: When the application get file status through local storage instead of AlluxioFuse, and only use AlluxioFuse to read data, the master memory is consistent at a low level.
Case 2: When the application list file status through AlluxioFuse, the memory suddenly increases to a large number. They feel the memory increases make sense, but they expect the memory to go back to the original level similar to case 1. But after the list status, even when list status is finished, the memory is at a relatively high level until stop world GC happens. And then the master keeps doing stop world GC. Within one hour, about half hour is doing the GC. 

![](https://files.slack.com/files-pri/TEXALQC8J-F02U0CT8KSM/image.png)

**Comment by LuQQiu** [comment]
@yuzhu FYI

**Comment by ggezer** [comment]
64GB of heap for ~20M files might not be sufficient. Did you try off-heap metadata store? https://docs.alluxio.io/ee/user/stable/en/operation/Metastore.html#rocksdb-metastore

Could you also share your master configuration?

**Comment by apc999** [comment]
@ggezer  this is using Fluid and by default Rocksdb is used

**Comment by apc999** [comment]
@Nizifan we have a working group to solve master memory issues these days. Hopefully we will get a new release with this issue mitigated or fixed shortly

**Comment by jiacheliu3** [comment]
When your JVM is seeing memory challenge, can you do `jmap -histo <master pid>` several times to see what are the top used objects? If you can run `jmap -histo:live <master pid>` to see the living objects that's even better. But do note that `:live` will perform a GC, which may cause your JVM to pause.

**Comment by LuQQiu** [comment]
@jiacheliu3 @yuzhu 
They set jvm config 
```
-XX:MaxGCPauseMillis=30 -XX:ParallelGCThreads=40
```
and then stop world GC  gone

**Comment by jiacheliu3** [comment]
@LuQQiu if you don't give jvm enough time to GC the memory will stack up. And when the JVM thinks it can no longer follow the contract, it breaks the contract by doing a full GC with 1 thread and STW.

**Comment by Nizifan** [comment]
@jiacheliu3 Looks like after setting this new contract, the jvm apply more aggressive policy on gc, never see stop world gc again in past 24 hours with a even higher workload. And gc happen at higher frequency to control the whole scale.
![image](https://user-images.githubusercontent.com/11472213/151137301-e1a97814-c128-4c2b-9fb4-6a51729efa28.png)

**Comment by jiacheliu3** [comment]
@Nizifan Glad to hear this works out for you. There are always more than one way to achieve a better GC pattern.

`-XX:ParallelGCThreads=40` will give you a better GC concurrency at the cost of more CPU usage.

Personally I'm not a big fan of `-XX:MaxGCPauseMillis=30` because I think if you set this number too low, the GC will not be able to collect enough garbage, and after a long time, your heap will grow large enough that it needs a full GC. Maybe 30ms is too low, depending on how interactive you want your JVM to be. In many Alluxio use cases people are running batch jobs which prefers throughput to responsiveness, so they can set this value higher to let GC do more work. And the time limit is just used to guard long pauses.

If you are using Java 8 your default GC is ParallelScavenger+ParallelOld. Personally I prefer to change that to ParNew+CMS which theoretically have better throughput, and many of our customers with >200G heaps are using that combination. You can have a try too. CMS has a default threshold of 65%, which means kicking off a concurrent major GC at 65% fullness in the heap.

**Comment by jiacheliu3** [comment]
If this issue is just about sub-optimal GC parameters, I think it can be closed as it's not really an Alluxio issue. 

Feel free to move this off line or submit changes to alluxio-env.sh if you feel better default JVM properties should be applied. Thx :)

**Comment by LuQQiu** [comment]
Mark it as closed for now. @Nizifan feel free to reopen the issue when needed, thanks @jiacheliu3 for helping out this issue

**Comment by yuzhu** [comment]
@jiacheliu3 should we update tuning docs to include this?

**Comment by jiacheliu3** [comment]
@yuzhu This looks more like GC tuning than Alluxio-specific tuning. I think it's fair to mention something like "If your Alluxio service is slow blah blah, check the jvm usage and try to tune." But there's no need to talk too much about GC. After all, each garbage collector can have many caveats and there's Java 11 (not to mention Java 11+).
