### ISSUE TITLE
Fluid DataLoader is extremely slow, take 5~20h on the same 300Gi dataset

### ISSUE THREAD

**Issue by Nizifan** [Alluxio/alluxio#14843]
**Alluxio Version:**
2.7.0

**Describe the bug**
I am going to open fluid DataLoader feature to user and when doing test, and I find performance is extremely bad.
I create 2 instance of Alluxio runtime on the same s3 ufs, and create DataLoader without "fetch metadata" option on.

The 300Gi dataset mainly consist of small pictures, mainly size around 100k so there will be 3 million files in the dataset.

root@10:~# k get dataload
NAME         DATASET       PHASE      AGE   DURATION
loadlingdu   ziyue-train   Complete   18h   6h53m45s
NAME                   DATASET       PHASE      AGE   DURATION
ziyue-train-dataload   ziyue-train   Complete   23h   22h57m8s

Take the second one as example, from monitor(monitor data have been lost, I will add it later), it stuck for first 10+ hour(without active read and Alluxio size keep 0), and read for 4 hours and complete load.

**Comment by LuQQiu** [comment]
@ssz1997 can you take a look to see
1. whether we can reproduce the behavior
2. is Fluid data load using distributedLoad?
3. are there low-hanging fruit? mainly in terms of configuration. I can help with this part. There could be some job service configuration and thread pool (including s3 thread pool) we can tune to see if we can improve the performance
4. are there more improvements we can do? how much effort needed?

**Comment by LuQQiu** [comment]
Find worker metrics, Worker issues `CommitBlock` requests to Master and takes `count * mean = 64h` total
```
    "Worker.CommitBlock.User:root.10.70.20.31": {
      "count": 13329763,
      "max": 4821.7695269999995,
      "mean": 17.37411890029415,
      "min": 0.217157,
      "p50": 0.29481999999999997,
      "p75": 0.335073,
      "p95": 0.491268,
      "p98": 2.043547,
      "p99": 5.514854,
      "p999": 4488.852707999999,
      "stddev": 268.6507147468672,
      "m15_rate": 3.2603280609616598e-18,
      "m1_rate": 4.2603323247057504e-299,
      "m5_rate": 2.4962103590496417e-58,
      "mean_rate": 20.246969823609746,
      "duration_units": "milliseconds",
      "rate_units": "calls/second"
    },
```
Code link: [https://github.com/Alluxio/alluxio/blob/4c8b555920da6a844f3f30cc70493b563178518d/core/server/worker/src/main/java/alluxio/worker/block/BlockMasterClient.java#L105](https://github.com/Alluxio/alluxio/blob/4c8b555920da6a844f3f30cc70493b563178518d/core/server/worker/src/main/java/alluxio/worker/block/BlockMasterClient.java#L105)


On the master side, master executes `CommitBlock` requests takes only `count * mean = about 8min`
```
"Master.commitBlock.User:root": {
      "count": 13329763,
      "max": 0.7744759999999999,
      "mean": 0.03578812787708019,
      "min": 0.013939,
      "p50": 0.031858,
      "p75": 0.040097999999999995,
      "p95": 0.057676,
      "p98": 0.068092,
      "p99": 0.08110099999999999,
      "p999": 0.7744759999999999,
      "stddev": 0.033484641480266336,
      "m15_rate": 4.106129612812308e-17,
      "m1_rate": 1.355184783084074e-282,
      "m5_rate": 4.986497534515744e-55,
      "mean_rate": 20.317372461724496,
      "duration_units": "milliseconds",
      "rate_units": "calls/second"
    },
```
Code link:[https://github.com/Alluxio/alluxio/blob/4c8b555920da6a844f3f30cc70493b563178518d/core/server/master/src/main/java/alluxio/master/block/BlockMasterWorkerServiceHandler.java#L97](https://github.com/Alluxio/alluxio/blob/4c8b555920da6a844f3f30cc70493b563178518d/core/server/master/src/main/java/alluxio/master/block/BlockMasterWorkerServiceHandler.java#L97)

The huge gap between how long worker takes to `commitBlock` and how long master takes to executes `commitBlock` indicates that something wrong between them, the hypothesis includes:
1. master RPC thread pool is relatively small, some worker gRPC threads are waiting for their requests to be executed. Since worker and client share the same thread pool, if a lot of client requests are executed, worker requests may need to wait.
2. Threads fighting for CPU/memory resources

**Comment by LuQQiu** [comment]
```
alluxio.worker.block.master.client.pool.size=1024 
alluxio.master.rpc.executor.core.pool.size=128
alluxio.master.rpc.executor.max.pool.size=1024 <-- enlarge this variable may help?
```

**Comment by LuQQiu** [comment]
Master memory setting is 64GB, worker memory setting is 32GB,
not quite sure what's the allocated CPU for master and worker.
Threads may be competing for CPU resources

**Comment by LuQQiu** [comment]
@yuzhu FYI, thanks!

**Comment by wukong1992** [comment]
> Find worker metrics, Worker issues `CommitBlock` requests to Master and takes `count * mean = 64h` total
> 
> ```
>     "Worker.CommitBlock.User:root.10.70.20.31": {
>       "count": 13329763,
>       "max": 4821.7695269999995,
>       "mean": 17.37411890029415,
>       "min": 0.217157,
>       "p50": 0.29481999999999997,
>       "p75": 0.335073,
>       "p95": 0.491268,
>       "p98": 2.043547,
>       "p99": 5.514854,
>       "p999": 4488.852707999999,
>       "stddev": 268.6507147468672,
>       "m15_rate": 3.2603280609616598e-18,
>       "m1_rate": 4.2603323247057504e-299,
>       "m5_rate": 2.4962103590496417e-58,
>       "mean_rate": 20.246969823609746,
>       "duration_units": "milliseconds",
>       "rate_units": "calls/second"
>     },
> ```
> 
> Code link:
> 
> https://github.com/Alluxio/alluxio/blob/4c8b555920da6a844f3f30cc70493b563178518d/core/server/worker/src/main/java/alluxio/worker/block/BlockMasterClient.java#L105
> 
> On the master side, master executes `CommitBlock` requests takes only `count * mean = about 8min`
> 
> ```
> "Master.commitBlock.User:root": {
>       "count": 13329763,
>       "max": 0.7744759999999999,
>       "mean": 0.03578812787708019,
>       "min": 0.013939,
>       "p50": 0.031858,
>       "p75": 0.040097999999999995,
>       "p95": 0.057676,
>       "p98": 0.068092,
>       "p99": 0.08110099999999999,
>       "p999": 0.7744759999999999,
>       "stddev": 0.033484641480266336,
>       "m15_rate": 4.106129612812308e-17,
>       "m1_rate": 1.355184783084074e-282,
>       "m5_rate": 4.986497534515744e-55,
>       "mean_rate": 20.317372461724496,
>       "duration_units": "milliseconds",
>       "rate_units": "calls/second"
>     },
> ```
> 
> Code link:
> 
> https://github.com/Alluxio/alluxio/blob/4c8b555920da6a844f3f30cc70493b563178518d/core/server/master/src/main/java/alluxio/master/block/BlockMasterWorkerServiceHandler.java#L97
> 
> The huge gap between how long worker takes to `commitBlock` and how long master takes to executes `commitBlock` indicates that something wrong between them, the hypothesis includes:
> 
> 1. master RPC thread pool is relatively small, some worker gRPC threads are waiting for their requests to be executed. Since worker and client share the same thread pool, if a lot of client requests are executed, worker requests may need to wait.
> 2. Threads fighting for CPU/memory resources

How to get these metrics.

**Comment by ssz1997** [comment]
@wukong1992 You can refer to this page in Alluxio doc: https://docs.alluxio.io/os/user/stable/en/operation/Metrics-System.html

**Comment by LuQQiu** [comment]
@ssz1997 can you help update the progress of this issue

**Comment by ssz1997** [comment]
Use VisualVM to profile master, worker, job master, and job worker, while the distributedLoad job is running.

CPU usages all look normal. Memory usages all look normal other than job worker. Job worker keeps requesting more heap space. If there's no bound through jvmOption, job worker eats up all available heap space. If there is a bound through jvmOption, job worker still eats up the allocated heap space and gc doesn't help. In both cases later on job worker stops responding requests.

Looking at heap dumps, we notice that `ConcurrentHashMap$Node[]` and `ConcurrentHashMap$Node` take most of the space, more than 60%. 

In job worker loading code, in this particular scenario, for each time `[loadBlock()](https://github.com/Alluxio/alluxio/blob/2cb9d9a994e7dd389bf1d30d93f3d522d4bf3123/job/server/src/main/java/alluxio/job/util/JobUtils.java#L231)` is called, we copy one `AlluxioConfiguration`, which contains two concurrent hashmaps. The heap dump also shows there are more than 114k `AlluxioConfiguration` objects. 

If we don't run this code snippet, for example run the new implementation of distributedLoad, the job worker heap usage stays low (< 5GB), which confirms the copies of `AlluxioConfiguration` is taking all the memory.

**Comment by jja725** [comment]
When running the test, the direct cache only uses around 1% of the CPU of the Worker while the passive cache could use up to 10%.

direct-cache constantly uses 4 threads running (which is core pool size) while passive-cache could use more threads(8 to 10).

The difference is caused by the different kinds of GRPC APIs. Which direct-cache uses blocking RPC(have to wait for the call to be finished so the request never fills up the thread pool queue) while passive-cache use a streaming RPC(which could have better performance for parallelism)

So the solution would be to transform blocking unary RPC to ASYNC unary RPC for better performance.

**Comment by ssz1997** [comment]
Fixed by https://github.com/Alluxio/alluxio/pull/15084 and https://github.com/Alluxio/alluxio/pull/15607
