### ISSUE TITLE
Worker didn't clean up space it used in docker disk when exit.

### ISSUE THREAD

**Issue by Nizifan** [Alluxio/alluxio#15172]
**Alluxio Version:**
2.7.2 + fluid v0.6

**Describe the bug**
When worker exit, it doesn't clean corresponding block on docker disk, cause disk become full:

root@jssz-main-cv-train-15:~ # du -h --max-depth=1 /data/docker/alluxio/ai/ 
0	/data/docker/alluxio/ai/xg-lid
489G	/data/docker/alluxio/ai/xingui-lid      <- this one is already deleted
375G	/data/docker/alluxio/ai/audf-1
863G	/data/docker/alluxio/ai/
root@jssz-main-cv-train-15:~ # df -h /data/docker/
Filesystem      Size  Used Avail Use% Mounted on
/dev/nvme0n1    1.5T  1.5T   20K 100% /data/docker

And the worker is no longer running:
root@jssz-main-cv-train-15:~ # docker ps | grep alluxio-worker
23af46fe6ea8        hub.bilibili.co/ops-coeus/alluxio-with-hdfs            "/entrypoint.sh work…"   3 days ago          Up 3 days                               k8s_alluxio-worker_audf-1-worker-mlgsc_ai_062c1835-7721-4752-8607-820f9c660752_0

**Comment by LuQQiu** [comment]
Fluid uses
```
timeout -t 60 alluxio fs free -f path
```
to clean the Alluxio cache

Two possibilities here:
1. timeout -t 60 is not enough for clearing data in Alluxio
2. `alluxio fs free -f /path` didn't actually clear all data in worker storage

**Comment by LuQQiu** [comment]
@ssz1997 can you help resolve the problem of how to cleanup worker disk data in the Kubernetes environment?

**Comment by ssz1997** [comment]
Depending on how you delete worker, especially in Fluid env, there may be different behaviors.

The fluid way is to delete the whole cluster by running `kubectl delete alluxioruntime`, which would run `alluxio fs free /`. As Lu pointed out, even this way might not clean up all the data. But I think this is not the root cause here. 

If you directly delete worker daemonset by running `kubectl delete daemonset xxxx-worker`, the data will not be deleted. Even after you delete pv and pvc created by Fluid, the data will still be there because the default pv reclaim policy provided by Fluid is `Retain`. The only way to delete these data in this case is to purge the data directly from the disk. See https://kubernetes.io/docs/concepts/storage/persistent-volumes/#retain. Not to mention Fluid will recreate the pv and the pvc.

For other ways to exit worker, we may have to see case by case whether the data is cleaned up.
