### ISSUE TITLE
alluxio/journal/raft/xx/log_ A large number of files, can this be cleaned?

### ISSUE THREAD

**Issue by liangrui1988** [Alluxio/alluxio#15974]
**Alluxio Version:**
2.7.2
**Describe the bug**
# df -h
Filesystem      Size  Used Avail Use% Mounted on
.....
/dev/sda3       185G  159G   17G  91% /data

root@fs-alluxio-master02:/data/alluxio/alluxio/journal/raft/02511d47-d67c-49a3-9011-abb3109a44c1/current# du -sh
154G    .

-rw-rw-r-- 1 alluxio alluxio 9.4M Jul 28 07:00 log_32984255-32985632
-rw-rw-r-- 1 alluxio alluxio 9.4M Jul 28 07:00 log_32985633-32985652
-rw-rw-r-- 1 alluxio alluxio  10M Jul 28 07:05 log_32985653-32985724
-rw-rw-r-- 1 alluxio alluxio  10M Jul 28 07:05 log_32985725-32985980
-rw-rw-r-- 1 alluxio alluxio  10M Jul 28 07:10 log_32985981-32986242
-rw-rw-r-- 1 alluxio alluxio  10M Jul 28 07:10 log_32986243-32986492
-rw-rw-r-- 1 alluxio alluxio  10M Jul 28 07:15 log_32986493-32986820
....

 A large number of files, can this be cleaned?

**Comment by codings-dan** [comment]
@liangrui1988 Hi liangrui, how many masters in your Alluxio cluster? Normally, after the cluster generates a snapshot, it will automatically clean up the redundant journals.

**Comment by liangrui1988** [comment]
@codings-dan 3 a master
It seems that it has not been cleaned up. Do you need to configure anything?
![image](https://user-images.githubusercontent.com/7435076/181718196-7b7a3606-f85f-4012-b519-c193ceca9220.png)

**Comment by codings-dan** [comment]
@liangrui1988 Now only the Alluxio standby master will generate snapshots. When the snapshot are generated, ratis will be called to purge the log to complete the cleanup. So you can see less space on other nodes. Since the Alluxio primary master does not generate snapshots by itself, but copies snapshots from other followers, there seems to be no cleanup logic here. 

I think there are two ways to solve this problem :
1. Manually switch the Alluxio Primary master to the standby Master, which can help clean up the log next take snapshot
2. Check /data/alluxio/alluxio/journal/raft/02511d47-d67c-49a3-9011-abb3109a44c1/sm/ to find the largest log id in the snapshot file, and then journals smaller than this id can be cleaned up.

However, I think a more elegant solution is to purge log after maybeCopySnapshotFromFollower on Alluxio primary master. Do you have any advice on this issue? @jenoudet

**Comment by jenoudet** [comment]
@liangrui1988 We have noticed the same issue as you and fixed it in #15245. After this fix, all logs cleanup properly after a snapshot installation, both on the leading master and the standby masters.
This PR and fix are available starting in Alluxio 2.8.

@codings-dan Thank you for bringing this question to my attention.

**Comment by HelloHorizon** [comment]
@jenoudet can we close this issue?

**Comment by jenoudet** [comment]
> @jenoudet can we close this issue?

I believe so.
