### ISSUE TITLE
Failed to get user in Kubernetes with helm chart

### ISSUE THREAD

**Issue by ssz1997** [Alluxio/alluxio#15979]
**Alluxio Version:**
Master

**Describe the bug**
User 1000 does not exist in the containers in k8s. Worker is unable to find the user and `login`, and thus cannot talk to master. The cluster can't start successfully.

**Comment by ZhuTopher** [comment]
This issue happens due to https://github.com/Alluxio/alluxio/pull/15898 being merged. That PR forces the Alluxio docker image to run as the root user.

Can we refactor the Dockerfile to create a different admin user with permission to create users/groups & assign file ownership (i.e: a sudo-er), but isn't root (uid=0, gid=0)? The rest will still be the same; after creating the alluxio user & group you run the process as that user. This is just so that the container image itself doesn't run with a root user (which is very dangerous if people can enter the container runtime somehow).
- Example blogpost: https://blog.aquasec.com/rootless-containers-boosting-container-security

**Comment by ssz1997** [comment]
The PR caused the problem was reverted. Close this issue.
