### ISSUE TITLE
java.lang.NoClassDefFoundError: alluxio/underfs/hdfs/HdfsUnderFileSystemFactory

### ISSUE THREAD

**Issue by coldwind6** [Alluxio/alluxio#17415]
**Alluxio Version:**
2.9.3

**Describe the bug**
When i run the command: ./alluxio validateEnv local 
i got the 1 failure  result and some warning

ip1 alluxio-site.properties:
![image](https://github.com/Alluxio/alluxio/assets/46366124/da9ff3d1-e87d-439b-adc2-4ccd629d2dd1)
ip1 masters:
192.168.0.217
192.168.0.218
ip1 works:
192.168.0.218
192.168.0.219

ip2 alluxio-site.properties:
![image](https://github.com/Alluxio/alluxio/assets/46366124/0d61cd0c-9311-4f5b-b701-d46ab12d2ba2)

ip2 masters:
192.168.0.217
192.168.0.218
ip2 works:
192.168.0.218
192.168.0.219

ip3 alluxio-site.properties:
![image](https://github.com/Alluxio/alluxio/assets/46366124/741400e4-4bd7-4839-a842-cf28ae43ca88)

ip3 masters:
192.168.0.217
192.168.0.218
ip3 works:
192.168.0.218
192.168.0.219

**Expected behavior**
show the failure reason and fix theNoClassDefFoundError

**Comment by ssz1997** [comment]
@coldwind6 The `bin/alluxio validateEnv` is mainly for validating HDFS as UFS. If you are not using HDFS as UFS, don't worry about it too much.

But looking at your configurations, I see you configure to launch 2 masters on 2 instances. This is against the logic of alluxio master. The number of masters must be an odd number because even number of masters cannot form a quorum to do leader election. Please fix this before you proceed to launch Alluxio cluster.

Feel free to submit more questions.

**Comment by coldwind6** [comment]
@ssz1997 I need use HDFS the next step. I think it's the jar conflict for HdfsUnderFileSystemFactory Class, can it resolve immediately？ Now, i don‘t know the scope cause by the NoClassDefFoundError in HDFS.
Then i have reslove the config for odd number masters.

**Comment by ssz1997** [comment]
Synced offline and resolve the problem. Thus close this issue.
