### ISSUE TITLE
I DON'T KNOW WHY

### ISSUE THREAD

**Issue by listenLearning** [Alluxio/alluxio#5868]
Today, I translated alluxio, and then installed, when the installation found in what I do not configure the situation will be able to start the master, but can not start the work of the situation, and then I configure the distribution of the time, but found A mistake, it suggested that can not find java home, but obviously I have configured java home, and then I use the official tar package to re-install, is still the problem, he returned to / usr / bin below to find my Java ([192.168.0.7] which: no java in (/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/ Usr / bin) ^ M), I modified (/root/alluxio-1.5.0-hadoop-2.6/libexec/alluxio-config.sh) inside the java home path, and alluxio-layout.sh.template java home Path, but still this problem, is this why

**Comment by apc999** [comment]
@listenLearning you are welcome to post your questions in user forum: https://groups.google.com/forum/?fromgroups#!forum/alluxio-users (or its mirror site http://apache-spark-user-list.1001560.n3.nabble.com/). Let me know if you have access it. Otherwise I will close this issue. We could discuss your issue there. thanks
