### ISSUE TITLE
读取数据时的缓存问题

### ISSUE THREAD

**Issue by joey71765** [Alluxio/alluxio#6868]
我使用nfs作为底层的共享存储，nfs在被Alluxio挂载前已经存在一些问题件，当我使用例如 copyToLocal 这种命令Alluxio读取原先存在nfs而并不存在于Alluxio中的文件时，读取文件后，文件并不会加载到alluxio，但我通过客户端上传文件时（copyFromLocal），会显示在in-alluxio中，是不是alluxio只缓存通过客户端写的文件，而原有的文件被读取时，不会缓存到？我们希望达到的目的是，当读取一个不存在Alluxio的文件时，能同时把该文件缓存到Alluxio中。
读写配置如下
alluxio.user.file.readtype.default=CACHE_PROMOTE
alluxio.user.file.writetype.default=CACHE_THROUGH
按照文档的描述，CACHE_PROMOTE应该就是会把文件缓存才对的，是不是我的理解或者配置有问题呢

**Comment by apc999** [comment]
we typically host Alluxio usage related questions in our mailing list (https://groups.google.com/forum/#!forum/alluxio-users)
as specified in https://github.com/Alluxio/alluxio/issues/329 .

For you particular question, https://www.alluxio.org/overview/dataflow has more detailed explanation. I think what's tricky here is  you need to pass `alluxio.user.file.readtype.default=CACHE_PROMOTE` in the correct way to your application. See https://www.alluxio.org/docs/1.7/en/Configuration-Settings.html#configure-applications for different applications.

Close your issue here and feel free to reach me (binfan@alluxio.com) if you have any question.

- Bin
