### ISSUE TITLE
Where is init.yml?

### ISSUE THREAD

**Issue by henryhyu** [Alluxio/alluxio#6898]
No way to test this with Vagrant if the files specify a need for init.yml when the file does not exist?

**Comment by apc999** [comment]
hi @henryhyu ,

we typically host Alluxio usage related questions in our mailing list (https://groups.google.com/forum/#!forum/alluxio-users)
as specified in https://github.com/Alluxio/alluxio/issues/329 .

Close your issue here and feel free to reach me (binfan@alluxio.com) if you have any question 

- Bin
