### ISSUE TITLE
if master also as worker node the console can not recognize master as worker node

### ISSUE THREAD

**Issue by perrywang** [Alluxio/alluxio#8662]
**Alluxio Version:**
1.8.1 release
**Describe the bug**
start master also as worker node
from \<master\>:19999 can not find this worker node
**To Reproduce**
start master also as worker node
access \<master\>:19999 can not find this worker node
**Expected behavior**
can recognize this worker node even it is also as master node
**Urgency**
intermediate
**Additional context**
N/A

**Comment by ZacBlanco** [comment]
Hi @perrywang  thanks for reporting this issue! Could you elaborate on what you mean by "start master also as worker node"?

Do you mean that you are starting a worker node on the same node that the master is on? If so, that should work as lots of local development is performed with the master+workers on the same node.

Any additional steps to reproduce (such as a list of shell commands) or a stack trace from a log could be useful in pinpointing the root cause of the issue. Anything helps!

**Comment by perrywang** [comment]
> Hi @perrywang thanks for reporting this issue! Could you elaborate on what you mean by "start master also as worker node"?
> 
> Do you mean that you are starting a worker node on the same node that the master is on? If so, that should work as lots of local development is performed with the master+workers on the same node.
> 
> Any additional steps to reproduce (such as a list of shell commands) or a stack trace from a log could be useful in pinpointing the root cause of the issue. Anything helps!
when I use alluxio-monitor.sh it is reporting worker node working fine and worker.log seems also working fine. But just I use browser console to view workers it is not showing.

**Comment by ZacBlanco** [comment]
It is possible that the worker isn't showing up in the master UI because it can't register with the master in the first place. Another possibility is that the worker is starting up, the monitor is detecting it, but the worker shuts down after the monitor sees it is up. It is hard to say exactly what's happening.

If you could provide the master/worker logs (`logs/master.log`, `logs/worker.log`), a configuration (alluxio-site.properties), and/or the exact set of commands you're running so I can reproduce the issue, it will help solve this faster.

**Comment by ZacBlanco** [comment]
Also, while the web UI _should_ always work, you can also try the master's REST API

```bash
curl -X GET http://<master_ip>:19999/api/v1/master/worker_info_list
```

**Comment by perrywang** [comment]
> Also, while the web UI _should_ always work, you can also try the master's REST API
> 
> ```shell
> curl -X GET http://<master_ip>:19999/api/v1/master/worker_info_list
> ```
> 
> If the worker has successfully registered with the master, the `master.log` should contain a line similar to the following:
> 
> ```
> 2019-04-02 01:05:52,796 INFO  DefaultBlockMaster - registerWorker(): MasterWorkerInfo{id=4062936956978226972, workerAddress=WorkerNetAddress{host=10.0.0.222, rpcPort=29999, dataPort=29999, webPort=30000, domainSocketPath=, tieredIdentity=TieredIdentity(node=10.0.0.222, rack=null)}, capacityBytes=11453246122, usedBytes=0, lastUpdatedTimeMs=1554192352796, blocks=[]}
> ```

It is interesting. I think it is related with how worker register its host address to master. 
I am using vagrant (virtualbox) and private network to install master and worker. I set masters 192.168.1.100 and workers 192.168.1.100.  And I run alluxio-start.sh all Mount. I did seen in the master log
`2019-04-02 01:37:13,795 INFO  DefaultBlockMaster - registerWorker(): MasterWorkerInfo{id=6947831682232198818, workerAddress=WorkerNetAddress{host=10.0.2.15, rpcPort=29998, dataPort=29999, webPort=30000, domainSocketPath=, tieredIdentity=TieredIdentity(node=10.0.2.15, rack=null)}, capacityBytes=6442450944, usedBytes=0, lastUpdatedTimeMs=1554194233789, blocks=[]}`

below is my ip addr command show,
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 08:00:27:a2:0e:2b brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global dynamic eth0
       valid_lft 50494sec preferred_lft 50494sec
    inet6 fe80::a00:27ff:fea2:e2b/64 scope link
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 08:00:27:90:64:49 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.100/24 brd 192.168.1.255 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe90:6449/64 scope link
       valid_lft forever preferred_lft forever
```
you can see it is using eth0 address and ignore my configuration. and also I can't see worker in browser. 
This is a big problem if the worker running on another node with two ip address. the master will get wrong ip of worker.

**Comment by ZacBlanco** [comment]
Thanks! This is helpful. If you're seeing the `registerWorker` in the master logs, then `curl -X GET http://<master_ip>:19999/api/v1/master/worker_info_list` should return a JSON object with at least one worker in it.

Is your vagrant setup using just one virtual machine? If so, I would run `./bin/alluxio-start.sh local Mount`. That should work without modifications. The worker does an address lookup to tell the master where it is located. The master however, will never initiate a connection with a worker. As long as the worker can reach the master everything should work fine.

Otherwise, if they are on separate VMs then both machines need to have different IP addresses. You previously mentioned:

>I set masters 192.168.1.100 and workers 192.168.1.100

If you are running separate machines on the same network they need different IPs. Your master can be at `192.168.1.100` and your worker can be on `192.168.1.101`. You can also force a worker to register using a specific hostname/IP address by setting `alluxio.worker.hostname`

**Comment by perrywang** [comment]
> alluxio.worker.hostname

Thanks. @ZacBlanco. alluxio.worker.hostname is the working solution. 
Thanks for your patience. Closing issue.
