### ISSUE TITLE
Slashes get converted to underscores in the metrics UI page

### ISSUE THREAD

**Issue by calvinjia** [Alluxio/alluxio#9179]
**Alluxio Version:**
2.0.0-SNAPSHOT

**Describe the bug**
The web UI escapes slashes `/` as underscores `_`. This is particularly bad in the metrics UI where Alluxio displays the under filesystem metrics.

**To Reproduce**
Deploy Alluxio with an under filesystem which has a `/`. Open the metrics tab and look at the under filesystem metrics.

**Expected behavior**
The under filesystem metrics are titled appropriately with `/`.

**Urgency**
Bad cosmetic bug, should be addressed before next release.

**Comment by jiacheliu3** [comment]
Please correct me if I'm wrong, I think this is cause by **alluxio/core/common/src/main/java/alluxio/metrics/MetricsSystem.java**
`  /**
   * Escapes a URI, replacing "/" and "." with "_" so that when the URI is used in a metric name,
   * the "/" and "." won't be interpreted as path separators.
   *
   * @param uri the URI to escape
   * @return the string representing the escaped URI
   */
  public static String escape(AlluxioURI uri) {
    return uri.toString().replace("/", "_").replace(".", "_");
  }
`
Dating back to https://github.com/Alluxio/alluxio/commit/a34aaeeb832b82aeb3747b27e342044291287fe1#diff-2430397f25c728733f428f222dbbde2a
Since this method is used in quite a few places I think this method should be kept as-is. And add another  un-escape before returning the metrics back to React UI or handle this in React. What do you think? @bf8086 @calvinjia

**Comment by jiacheliu3** [comment]
Confirmed changing
```java
return uri.toString().replace("/", "_").replace(".", "_");
```
To
```java
return uri.toString().replace(".", "_");
```
met the expected behavior. But I don't think this is the way to go unless we invalidate the reason of escaping the URI.

**Comment by bf8086** [comment]
@calvinjia do you know why we need to escape `/`? It seems the metrics library only use `.` as a separator.

**Comment by bf8086** [comment]
PR: https://github.com/Alluxio/alluxio/pull/9265
