### ISSUE TITLE
Transparent URI

### ISSUE THREAD

**Issue by yuzhu** [Alluxio/alluxio#9231]
**Is your feature request related to a problem? Please describe.**
Alluxio users often switch between accessing UFS directly and using Alluxio to access the data. In this process, they need to switch URI from something like s3a:// ... to alluxio://... . Sometimes making this change is easy, but in some cases, making this change is difficult because it could be long-lived, as is the case when using Hive metastore.

**Describe the solution you'd like**
Compute frameworks define the mapping from FileSystem scheme to FileSystem implementation. Instead of switching all URI usages from hdfs -> alluxio, switch the FileSystem scheme mapping so that URIs with hdfs:// schemes are routed to Alluxio's FileSystem implementation. Then users can enable Alluxio with nothing but a configuration update.

**Urgency**
Alluxio 2.1

**Comment by liuzx32** [comment]
fs.s3.impl or fs.hdfs.impl can't directly depend on Alluxio's FileSystem, because Alluxio's FileSystem will check the scheme and the method getCheme() only return one sheme.
The scheme checking will throw exceptions below:  (s3 or hdfs)
-ls: URI scheme s3 does not match the expected scheme alluxio 
-ls: URI scheme hdfs does not match the expected scheme alluxio 
#

**Comment by yuzhu** [comment]
@liuzx32 I think the intention of this issue is to change the logic in Alluxio's File System so that we can use URI schemes such as s3 and hdfs directly. Currently they won't work, because Alluxio File System expect alluxio scheme.

**Comment by liuzx32** [comment]
@yuzhu Yes, we have the same mind.

**Comment by ggezer** [comment]
Some low-level details on this issue:

There will be a new file system implementation called `ShimFileSystem` that could be passed in `fs.***.impl`.

`ShimFileSystem` will simply forward every request to master without doing any URI check. On master, a reverse-lookup will be done against active Alluxio mount points and given URI will be converted on the fly to Alluxio path. 

For example:
- Application, with `ShimFileSystem` configured for `fs.s3.impl`, accesses `s3://some-bucket/foo/bar`.
- `ShimFileSystem` relays the request to Alluxio with original URI. 
- Alluxio detects `some-bucket` s3 bucket is already mounted at `/s3-buckets/some-bucket`.
- Given URI is transparently translated to alluxio://s3-buckets/some-bucket/foo/bar` and request is served.

The assumption here is that, data should be mounted in Alluxio for reverse-lookup to be able to correctly translate foreign schemes to Alluxio scheme. For when data is not mounted to Alluxio, we are planning to employ an auto-mount strategy using which unknown file systems will be attempted to be mounted on-demand using user supplied mount credentials/configs. This sceanrio will be addressed on a separate effort.

**Comment by puneetjaiswal** [comment]
We are interested using `Alluxio` with `Presto` but we don't want to point our write path to `AlluxioFS` (since we have thousands of DAGs and changing write path would be very disruptive) which happens mostly via Apache-`Hive/Spark/Flink` as of today.
We are having some workload that run `CTAS` on presto which generates tables in `S3` and queryable by hive as well.
How would the `ShimFileSystem` behave for data generated by `Presto` through `CTAS` like queries?

**Comment by ns1123** [comment]
@puneetjaiswal in the case of Presto, there are some specific limitations. Presto hardcodes the 'fs.s3.impl' property based on the 'hive.s3-file-system-type' property on the Hive connector. This property only allows for two possible values: EMRFS and PRESTO. Due to this, there is no entrypoint for users to specify that s3:// schemes should be read using the alluxio.hadoop.ShimFileSystem classes. You could potentially make the change in the Presto source code and rebuild, but that may be a little more involved. If this blocker were addressed, then we could potentially leverage the ShimFS for Presto as well. We only recently discovered this limitation, but hopefully the Presto community will be receptive in providing a more general solution for external S3 connector providers.

Links to relevant files:
[Hardcoded Impl](https://github.com/prestodb/presto/blob/3060c65a1812c6c8b0c2ab725b0184dbad67f0ed/presto-hive/src/main/java/com/facebook/presto/hive/s3/PrestoS3ConfigurationUpdater.java)
[Property Value Check](https://github.com/prestodb/presto/blob/3060c65a1812c6c8b0c2ab725b0184dbad67f0ed/presto-hive/src/main/java/com/facebook/presto/hive/s3/HiveS3Module.java)
