### ISSUE TITLE
will alluxio alluxio implement the tensorflow filesystem

### ISSUE THREAD

**Issue by myg821561935** [Alluxio/alluxio#9385]
We want to use alluxio as the unified storage middle layer. It would be very helpful if tensorflow had direct access to alluxio.

**Comment by ZacBlanco** [comment]
Hi @myg821561935 I believe using alluxio-fuse you can have tensor access data through Alluxio. Have you read through our documentation?

https://docs.alluxio.io/os/user/stable/en/compute/Tensorflow.html?q=tensorflow

Is there something in this guide that isn't compatible with your tensorflow setup?

**Comment by myg821561935** [comment]
Thank you very much for your reply, the fuse function is very useful for the tensorflow stand-alone mode. However, if I run a distributed version of tensorflow, do I need to mount the file on each node? Is this too much trouble?

**Comment by ZacBlanco** [comment]
No problem!

And yes, in this case, in order to run distributed tensorflow with Alluxio, you'll need to make the same Alluxio-fuse mount across your entire system.

Doing so allows Alluxio to provide locality and caching benefits to each node in your tensorflow cluster. Using a mount on a single machine won't be able to provide the same performance benefits.

It should not be too difficult to do this across a whole cluster with common deployment methods.
